colorspaces::ImageHSV8
const Image::FormatPtr colorspaces::ImageHSV8::FORMAT_HSV8
Referenced by colorspaces::Image::clone, colorspaces::ImageRGB8::imageCvt, colorspaces::ImageRGB8::toHSV8, imageCvt.
colorspaces::ImageHSV8::ImageHSV8(const int width, const int height)
Constructor
Referenced by createInstance.
colorspaces::ImageHSV8::ImageHSV8(const int width, const int height, void *const data)
Constructor from user data
colorspaces::ImageHSV8::ImageHSV8(const Image &i)
Copy constructor. if i doesn't match format a conversion will happen.
References colorspaces::Image::convert.
void colorspaces::ImageHSV8::toRGB8(Image &dst) const
Conversion methods. Returns a copy
References colorspaces::ImageRGB8::FORMAT_RGB8.
Referenced by imageCvt.
Image * colorspaces::ImageHSV8::createInstance(const int width, const int height, void *const data)
Factory method
References ImageHSV8.
Referenced by colorspaces::Image::clone.
Image & colorspaces::ImageHSV8::imageCvt(const Image &src, Image &dst)
References FORMAT_HSV8, colorspaces::ImageRGB8::FORMAT_RGB8, toRGB8.
Referenced by colorspaces::Image::clone.