colorspaces::ImageGRAY8
const Image::FormatPtr colorspaces::ImageGRAY8::FORMAT_GRAY8
Referenced by CameraUtils::getImageFromCameraProxy, CameraUtils::negotiateDefaultFormat, colorspaces::Image::clone, colorspaces::ImageRGB8::imageCvt, colorspaces::ImageRGB8::toGRAY8, colorspaces::ImageYUY2::imageCvt, colorspaces::ImageYUY2::toGRAY8, read, imageCvt, toYUY2, colorspaces::ImageNV21::toGRAY8.
const Image::FormatPtr colorspaces::ImageGRAY8::FORMAT_GRAY8_Z
Referenced by CameraUtils::getImageFromCameraProxy, CameraUtils::negotiateDefaultFormat, colorspaces::Image::clone.
colorspaces::ImageGRAY8::ImageGRAY8(const int width, const int height)
Constructor
Referenced by read, createInstance.
colorspaces::ImageGRAY8::ImageGRAY8(const int width, const int height, void *const data)
Constructor from user data
colorspaces::ImageGRAY8::ImageGRAY8(const Image &i)
Copy constructor. if i doesn't match format a conversion will happen.
References colorspaces::Image::convert.
void colorspaces::ImageGRAY8::toRGB8(Image &dst) const
Conversion methods. Returns a copy
References colorspaces::ImageRGB8::FORMAT_RGB8.
Referenced by imageCvt.
void colorspaces::ImageGRAY8::toYUY2(Image &dst) const
References colorspaces::ImageYUY2::FORMAT_YUY2, colorspaces::Image::width, colorspaces::Image::height, FORMAT_GRAY8.
Referenced by imageCvt.
bool colorspaces::ImageGRAY8::write(const std::string &filename, const std::vector< int > &params=std::vector< int >())
Write to a file See cv::imwrite for flags and params
ImageGRAY8 colorspaces::ImageGRAY8::read(const std::string &filename)
Read from a file See cv::imread for flags and params
References ImageGRAY8, colorspaces::Image::Image, FORMAT_GRAY8.
Image * colorspaces::ImageGRAY8::createInstance(const int width, const int height, void *const data)
Factory method
References ImageGRAY8.
Referenced by colorspaces::Image::clone.
Image & colorspaces::ImageGRAY8::imageCvt(const Image &src, Image &dst)
References FORMAT_GRAY8, colorspaces::ImageYUY2::FORMAT_YUY2, toYUY2, colorspaces::ImageRGB8::FORMAT_RGB8, toRGB8.
Referenced by colorspaces::Image::clone.