colorspaces::ImageYCRCB
const Image::FormatPtr colorspaces::ImageYCRCB::FORMAT_YCRCB
Referenced by colorspaces::Image::clone, colorspaces::ImageRGB8::imageCvt, colorspaces::ImageRGB8::toYCRCB, colorspaces::ImageYUY2::imageCvt, colorspaces::ImageYUY2::toYCRCB, imageCvt, colorspaces::ImageNV21::toYCRCB.
colorspaces::ImageYCRCB::ImageYCRCB(const int width, const int height)
Constructor
Referenced by createInstance.
colorspaces::ImageYCRCB::ImageYCRCB(const int width, const int height, void *const data)
Constructor from user data
colorspaces::ImageYCRCB::ImageYCRCB(const Image &i)
Copy constructor. if i doesn't match format a conversion will happen.
References colorspaces::Image::convert.
void colorspaces::ImageYCRCB::toRGB8(Image &dst) const
Conversion methods. Returns a copy
References colorspaces::ImageRGB8::FORMAT_RGB8.
Referenced by imageCvt.
Image * colorspaces::ImageYCRCB::createInstance(const int width, const int height, void *const data)
Factory method
References ImageYCRCB.
Referenced by colorspaces::Image::clone.
Image & colorspaces::ImageYCRCB::imageCvt(const Image &src, Image &dst)
References FORMAT_YCRCB, colorspaces::ImageRGB8::FORMAT_RGB8, toRGB8.
Referenced by colorspaces::Image::clone.