Tree
Tree* Tree::parent
std::string Tree::className
std::vector<Tree*> Tree::children
Tree::Tree(std::string filename)
References setClassName, Tree, fillSubTree.
Tree::Tree()
Referenced by Tree, fillSubTree.
void Tree::fillSubTree(boost::property_tree::ptree tree, Tree *root)
References setClassName, Tree.
Referenced by Tree.
void Tree::printClassName()
void Tree::printChildren()
void Tree::printChildrenRecursive()
void Tree::setClassName(std::string passedClassName)
Referenced by Tree, fillSubTree.
void Tree::insertChild(Tree *child)
References setParent.
void Tree::setParent(Tree *parent)
Referenced by insertChild.
Tree * Tree::searchTree(std::string className)
References searchTree.
Referenced by searchTree, getImmediateSynonmys.
std::vector< std::string > Tree::getImmediateSynonmys(std::string passedClassName)
References searchTree.
Referenced by ClassTypeMapper::mapString.