Config::Properties
YAML::Node Config::Properties::node
Config::Properties::Properties()
Config::Properties::Properties(YAML::Node node)
void Config::Properties::showConfig()
References printNode.
Referenced by SampleGenerationApp::verifyRequirements.
void Config::Properties::printNode(YAML::Node node, int nesting_level)
Referenced by showConfig.
bool Config::Properties::keyExists(std::string element)
References std::split, NodeExists.
Referenced by SampleGenerationApp::verifyRequirements.
bool Config::Properties::NodeExists(YAML::Node n, std::vector< std::string > names)
Referenced by keyExists.
YAML::Node Config::Properties::getNode(std::string element)
References std::split.
Referenced by MyApp::operator(), Config::operator<<.
std::string Config::Properties::asString(std::string element)
returns as string the propery given
route to element separated by dots (example: "carViz.Camera.proxy")
References std::split.
Referenced by MainWindow::~MainWindow, MyApp::operator(), Comm::getCameraClient, Comm::CameraIceClient::CameraIceClient.
std::string Config::Properties::asStringWithDefault(std::string element, std::string dataDefault)
returns as string the propery given
route to element separated by dots (example: "carViz.Camera.proxy") default value
References std::split.
Referenced by Comm::getCameraClient, Comm::CameraIceClient::CameraIceClient.
float Config::Properties::asFloat(std::string element)
returns as float the propery given
route to element separated by dots (example: "carViz.Camera.proxy")
References std::split.
float Config::Properties::asFloatWithDefault(std::string element, float dataDefault)
returns as float the propery given
route to element separated by dots (example: "carViz.Camera.proxy") default value
References std::split.
Referenced by Comm::CameraIceClient::CameraIceClient.
int Config::Properties::asInt(std::string element)
returns as integer the propery given
route to element separated by dots (example: "carViz.Camera.proxy")
References std::split.
int Config::Properties::asIntWithDefault(std::string element, int dataDefault)
returns as integer the propery given
route to element separated by dots (example: "carViz.Camera.proxy") default value
References std::split.
double Config::Properties::asDouble(std::string element)
returns as double the propery given
route to element separated by dots (example: "carViz.Camera.proxy")
References std::split.
double Config::Properties::asDoubleWithDefault(std::string element, double dataDefault)
returns as double the propery given
route to element separated by dots (example: "carViz.Camera.proxy") default value
References std::split.
YAML::Node Config::Properties::getNode()
YAML::Node Config::Properties::searchNode(YAML::Node n, std::vector< std::string > names)
makes recursively sear for element given in names
yaml node in which search vector of elements names (route to element of last position of vector) yaml node of element