colorspaces::Image
typedef Image*(* colorspaces::Image::imageCtor) (const int height, const int width, void *const data))(const int height, const int width, void *const data)
typedef Image&(* colorspaces::Image::imageCvt) (const Image &src, Image &dst))(const Image &src, Image &dst)
typedef std::shared_ptr<Format> colorspaces::Image::FormatPtr
int colorspaces::Image::width
Referenced by CameraUtils::getImageFromCameraProxy, colorspaces::ImageRGB8::toYUY2, colorspaces::ImageYUY2::toRGB8, colorspaces::ImageYUY2::toYCRCB, colorspaces::ImageGRAY8::toYUY2, colorspaces::ImageNV21::toRGB8, operator<<.
int colorspaces::Image::height
Referenced by CameraUtils::getImageFromCameraProxy, colorspaces::ImageRGB8::toYUY2, colorspaces::ImageYUY2::toYCRCB, colorspaces::ImageGRAY8::toYUY2, colorspaces::ImageNV21::toRGB8, operator<<.
const Image::FormatPtr colorspaces::Image::FORMAT_NONE
Referenced by clone.
FormatPtr colorspaces::Image::_format
colorspaces::Image::Image()
Constructor
Referenced by colorspaces::ImageRGB8::read, colorspaces::ImageGRAY8::read.
colorspaces::Image::Image(const int width, const int height, const FormatPtr fmt)
Constructor
colorspaces::Image::Image(const int width, const int height, const FormatPtr fmt, void *const data)
Constructor from user data
colorspaces::Image::Image(const Image &i)
Copy onstructor
colorspaces::Image::Image(const cv::Mat &m, const FormatPtr fmt)
Copy onstructor from cv::Mat
virtual colorspaces::Image::~Image()
Image destructor
const FormatPtr colorspaces::Image::format() const
Get image's format
References convert, clone.
Referenced by operator<<.
Image & colorspaces::Image::convert(Image &dst) const
Convert image to dst fmt
Referenced by colorspaces::ImageRGB8::ImageRGB8, colorspaces::ImageYUY2::ImageYUY2, colorspaces::ImageGRAY8::ImageGRAY8, colorspaces::ImageHSV8::ImageHSV8, colorspaces::ImageYCRCB::ImageYCRCB, colorspaces::ImageNV21::ImageNV21, format.
Image colorspaces::Image::clone() const
Clone image returning a new copy
References FORMAT_NONE, colorspaces::Image::Format::createFormat, colorspaces::ImageRGB8::FORMAT_RGB8, colorspaces::ImageRGB8::createInstance, colorspaces::ImageRGB8::imageCvt, colorspaces::ImageRGB8::FORMAT_RGB8_Z, colorspaces::ImageRGB8::FORMAT_DEPTH8_16, colorspaces::ImageRGB8::FORMAT_DEPTH8_16_Z, colorspaces::ImageYUY2::FORMAT_YUY2, colorspaces::ImageYUY2::createInstance, colorspaces::ImageYUY2::imageCvt, colorspaces::ImageGRAY8::FORMAT_GRAY8, colorspaces::ImageGRAY8::createInstance, colorspaces::ImageGRAY8::imageCvt, colorspaces::ImageGRAY8::FORMAT_GRAY8_Z, colorspaces::ImageHSV8::FORMAT_HSV8, colorspaces::ImageHSV8::createInstance, colorspaces::ImageHSV8::imageCvt, colorspaces::ImageYCRCB::FORMAT_YCRCB, colorspaces::ImageYCRCB::createInstance, colorspaces::ImageYCRCB::imageCvt, colorspaces::ImageNV21::FORMAT_NV21, colorspaces::ImageNV21::createInstance, colorspaces::ImageNV21::imageCvt.
Referenced by format.