ListViewConfig
bool ListViewConfig::configureDatasetInput(QMainWindow *mainWindow, QListView *qlistView, const std::string &path, bool multipleSelection)
References loadImage.path.
Referenced by MainWindow::~MainWindow.
bool ListViewConfig::configureInputByFile(QMainWindow *mainWindow, QListView *qlistView, const std::string &path, bool multipleSelection)
References loadImage.path.
Referenced by MainWindow::~MainWindow.
bool ListViewConfig::configureInputByData(QMainWindow *mainWindow, QListView *qlistView, const std::vector< std::string > &data, bool multipleSelection)
Referenced by MainWindow::~MainWindow.
void ListViewConfig::getPathContentDatasetInput(const std::string &path, std::vector< std::string > &content)
void ListViewConfig::getPathContentOnlyFiles(const std::string &path, std::vector< std::string > &content)