colorspaces::ImageYUY2
const Image::FormatPtr colorspaces::ImageYUY2::FORMAT_YUY2
Referenced by colorspaces::Image::clone, colorspaces::ImageRGB8::imageCvt, colorspaces::ImageRGB8::toYUY2, imageCvt, colorspaces::ImageGRAY8::imageCvt, colorspaces::ImageGRAY8::toYUY2.
colorspaces::ImageYUY2::ImageYUY2(const int width, const int height)
Constructor Width have to be an even number.
Referenced by createInstance.
colorspaces::ImageYUY2::ImageYUY2(const int width, const int height, void *const data)
Constructor from user data Width have to be an even number.
colorspaces::ImageYUY2::ImageYUY2(const Image &i)
Copy constructor. if i doesn't match format a conversion will happen.
References colorspaces::Image::convert.
void colorspaces::ImageYUY2::toGRAY8(Image &dst) const
Conversion methods. Returns a copy
References colorspaces::ImageGRAY8::FORMAT_GRAY8.
Referenced by imageCvt.
void colorspaces::ImageYUY2::toRGB8(Image &dst) const
References colorspaces::ImageRGB8::FORMAT_RGB8, colorspaces::Image::width, toYCRCB.
Referenced by imageCvt.
void colorspaces::ImageYUY2::toYCRCB(Image &dst) const
References colorspaces::ImageYCRCB::FORMAT_YCRCB, colorspaces::Image::height, colorspaces::Image::width.
Referenced by imageCvt, toRGB8.
Image * colorspaces::ImageYUY2::createInstance(const int width, const int height, void *const data)
Factory method
References ImageYUY2.
Referenced by colorspaces::Image::clone.
Image & colorspaces::ImageYUY2::imageCvt(const Image &src, Image &dst)
References FORMAT_YUY2, colorspaces::ImageRGB8::FORMAT_RGB8, toRGB8, colorspaces::ImageGRAY8::FORMAT_GRAY8, toGRAY8, colorspaces::ImageYCRCB::FORMAT_YCRCB, toYCRCB.
Referenced by colorspaces::Image::clone.