colorspaces::ImageNV21
const Image::FormatPtr colorspaces::ImageNV21::FORMAT_NV21
Referenced by colorspaces::Image::clone, imageCvt.
colorspaces::ImageNV21::ImageNV21(const int width, const int height)
Constructor Width have to be an even number.
Referenced by createInstance.
colorspaces::ImageNV21::ImageNV21(const int width, const int height, void *const data)
Constructor from user data Width have to be an even number.
colorspaces::ImageNV21::ImageNV21(const Image &i)
Copy constructor. if i doesn't match format a conversion will happen.
References colorspaces::Image::convert.
void colorspaces::ImageNV21::toGRAY8(Image &dst) const
Conversion methods. Returns a copy
References colorspaces::ImageGRAY8::FORMAT_GRAY8.
void colorspaces::ImageNV21::toRGB8(Image &dst) const
References colorspaces::ImageRGB8::FORMAT_RGB8, colorspaces::Image::width, colorspaces::Image::height.
Referenced by imageCvt, toYCRCB.
void colorspaces::ImageNV21::toYCRCB(Image &dst) const
References colorspaces::ImageYCRCB::FORMAT_YCRCB, toRGB8.
Image * colorspaces::ImageNV21::createInstance(const int width, const int height, void *const data)
Factory method
References ImageNV21.
Referenced by colorspaces::Image::clone.
Image & colorspaces::ImageNV21::imageCvt(const Image &src, Image &dst)
References FORMAT_NV21, colorspaces::ImageRGB8::FORMAT_RGB8, toRGB8.
Referenced by colorspaces::Image::clone.