SampleGeneratorHandler::SamplerGenerationHandler
GenericDatasetReaderPtr SampleGeneratorHandler::SamplerGenerationHandler::createDatasetReaderPtr(const QListView *datasetList, const QListView *namesList, const QListView *readerImpList, const QListView *filterClasses, const std::string &datasetPath, const std::string &namesPath, const bool imagesRequired)
References Utils::getListViewContent.
Referenced by SampleGeneratorHandler::Converter::process, SampleGeneratorHandler::Detector::process, SampleGeneratorHandler::Evaluator::process, SampleGeneratorHandler::Viewer::process.
GenericLiveReaderPtr SampleGeneratorHandler::SamplerGenerationHandler::createLiveReaderPtr(const QListView *namesList, const QListView *readerImpList, const QGroupBox *deployer_params, const QGroupBox *camera_params, const std::string &infoPath, const std::string &namesPath)
References Utils::getListViewContent, Utils::getCameraParamsContent, Utils::getDeployerParamsContent.
Referenced by SampleGeneratorHandler::Deployer::process.