PathHelper
std::string PathHelper::concatPaths(const std::string &p1, const std::string &p2)
References getPathSeparator.
Referenced by RecorderReader::RecorderReader, PrincetonDatasetReader::appendDataset.
std::string PathHelper::getPathSeparator()
Referenced by concatPaths.