TensorFlowInferencer
std::string TensorFlowInferencer::netConfig
std::string TensorFlowInferencer::netWeights
PyObject* TensorFlowInferencer::pName
PyObject * TensorFlowInferencer::pModule
PyObject * TensorFlowInferencer::pClass
PyObject * TensorFlowInferencer::pInstance
PyObject* TensorFlowInferencer::pArgs
PyObject * TensorFlowInferencer::pValue
PyObject * TensorFlowInferencer::pmodel
std::vector<detection> TensorFlowInferencer::detections
bool TensorFlowInferencer::hasMasks
TensorFlowInferencer::TensorFlowInferencer(const std::string &netConfig, const std::string &netWeights, const std::string &classNamesFile)
References FrameworkInferencer::classNamesFile, init.
Sample TensorFlowInferencer::detectImp(const cv::Mat &image, double confidence_threshold)
References gettfInferences, FrameworkInferencer::classNamesFile, ClassTypeGeneric::setId, ClassType::getClassString, Sample::setColorImage, Sample::setRectRegions, Sample::setRleRegions.
int TensorFlowInferencer::gettfInferences(const cv::Mat &image, double confidence_threshold)
References output_result.
Referenced by detectImp.
void TensorFlowInferencer::output_result(int num_detections, int width, int height, PyObject *bounding_boxes, PyObject *detection_scores, PyObject *classIds, PyObject *detections_masks=NULL)
References tensorflow_detect.threshold, rleEncode.
Referenced by gettfInferences.
void TensorFlowInferencer::init()
Referenced by TensorFlowInferencer.