Utils
bool Utils::getListViewContent(const QListView *list, std::vector< std::string > &content, const std::string &prefix)
Referenced by MainWindow::~MainWindow, SampleGeneratorHandler::Converter::process, SampleGeneratorHandler::Deployer::process, SampleGeneratorHandler::Detector::process, SampleGeneratorHandler::SamplerGenerationHandler::createDatasetReaderPtr, SampleGeneratorHandler::SamplerGenerationHandler::createLiveReaderPtr, SampleGeneratorHandler::Viewer::process.
bool Utils::getDeployerParamsContent(const QGroupBox *deployer_params, std::map< std::string, std::string > &deployer_params_map)
Referenced by SampleGeneratorHandler::SamplerGenerationHandler::createLiveReaderPtr.
bool Utils::getInferencerParamsContent(const QGroupBox *inferencer_params, std::map< std::string, std::string > &inferencer_params_map)
Referenced by SampleGeneratorHandler::Deployer::process, SampleGeneratorHandler::Detector::process.
bool Utils::getCameraParamsContent(const QGroupBox *camera_params, int &cameraID)
Referenced by SampleGeneratorHandler::SamplerGenerationHandler::createLiveReaderPtr.