colorspaces::ImageRGB8
const Image::FormatPtr colorspaces::ImageRGB8::FORMAT_RGB8
Referenced by CameraUtils::getImageFromCameraProxy, CameraUtils::negotiateDefaultFormat, CameraUtils::convert, colorspaces::Image::clone, read, imageCvt, colorspaces::ImageYUY2::imageCvt, colorspaces::ImageYUY2::toRGB8, colorspaces::ImageGRAY8::imageCvt, colorspaces::ImageGRAY8::toRGB8, colorspaces::ImageHSV8::imageCvt, colorspaces::ImageHSV8::toRGB8, colorspaces::ImageYCRCB::imageCvt, colorspaces::ImageYCRCB::toRGB8, colorspaces::ImageNV21::imageCvt, colorspaces::ImageNV21::toRGB8.
const Image::FormatPtr colorspaces::ImageRGB8::FORMAT_RGB8_Z
Referenced by CameraUtils::getImageFromCameraProxy, CameraUtils::negotiateDefaultFormat, colorspaces::Image::clone, imageCvt.
const Image::FormatPtr colorspaces::ImageRGB8::FORMAT_DEPTH8_16
Referenced by CameraUtils::getImageFromCameraProxy, CameraUtils::negotiateDefaultFormat, colorspaces::Image::clone, imageCvt.
const Image::FormatPtr colorspaces::ImageRGB8::FORMAT_DEPTH8_16_Z
Referenced by CameraUtils::getImageFromCameraProxy, CameraUtils::negotiateDefaultFormat, colorspaces::Image::clone, imageCvt.
colorspaces::ImageRGB8::ImageRGB8(const int width, const int height)
Constructor
Referenced by read, createInstance.
colorspaces::ImageRGB8::ImageRGB8(const int width, const int height, void *const data)
Constructor from user data
colorspaces::ImageRGB8::ImageRGB8(const Image &i)
Copy constructor from Image, conversion will happen if needed
References colorspaces::Image::convert.
void colorspaces::ImageRGB8::toGRAY8(Image &dst) const
Conversion methods.
References colorspaces::ImageGRAY8::FORMAT_GRAY8.
Referenced by imageCvt.
void colorspaces::ImageRGB8::toYUY2(Image &dst) const
References colorspaces::ImageYUY2::FORMAT_YUY2, colorspaces::Image::width, colorspaces::Image::height.
Referenced by imageCvt.
void colorspaces::ImageRGB8::toHSV8(Image &dst) const
References colorspaces::ImageHSV8::FORMAT_HSV8.
Referenced by imageCvt.
void colorspaces::ImageRGB8::toYCRCB(Image &dst) const
References colorspaces::ImageYCRCB::FORMAT_YCRCB.
Referenced by imageCvt.
bool colorspaces::ImageRGB8::write(const std::string &filename, const std::vector< int > &params=std::vector< int >())
Write to a file See cv::imwrite for flags and params
ImageRGB8 colorspaces::ImageRGB8::read(const std::string &filename)
Read from a file See cv::imread for flags and params
References ImageRGB8, colorspaces::Image::Image, FORMAT_RGB8.
Image * colorspaces::ImageRGB8::createInstance(const int width, const int height, void *const data)
Factory method
References ImageRGB8.
Referenced by colorspaces::Image::clone.
Image & colorspaces::ImageRGB8::imageCvt(const Image &src, Image &dst)
References FORMAT_RGB8, FORMAT_RGB8_Z, FORMAT_DEPTH8_16, FORMAT_DEPTH8_16_Z, colorspaces::ImageYUY2::FORMAT_YUY2, toYUY2, colorspaces::ImageGRAY8::FORMAT_GRAY8, toGRAY8, colorspaces::ImageYCRCB::FORMAT_YCRCB, toYCRCB, colorspaces::ImageHSV8::FORMAT_HSV8, toHSV8.
Referenced by colorspaces::Image::clone.