KerasInferencer
std::string KerasInferencer::netConfig
std::string KerasInferencer::netWeights
PyObject* KerasInferencer::pName
PyObject * KerasInferencer::pModule
PyObject * KerasInferencer::pClass
PyObject * KerasInferencer::pInstance
PyObject* KerasInferencer::pArgs
PyObject * KerasInferencer::pValue
PyObject * KerasInferencer::pmodel
std::vector<detection> KerasInferencer::detections
KerasInferencer::KerasInferencer(const std::string &netConfig, const std::string &netWeights, const std::string &classNamesFile)
References FrameworkInferencer::classNamesFile, init.
Sample KerasInferencer::detectImp(const cv::Mat &image, double confidence_threshold)
References getKerasInferences, FrameworkInferencer::classNamesFile, ClassTypeGeneric::setId, ClassType::getClassString, Sample::setColorImage, Sample::setRectRegions.
int KerasInferencer::getKerasInferences(const cv::Mat &image, double confidence_threshold)
References output_result.
Referenced by detectImp.
void KerasInferencer::output_result(PyObject *result, int sizes[])
Referenced by getKerasInferences.
void KerasInferencer::init()
Referenced by KerasInferencer.