MassInferencer
DatasetReaderPtr MassInferencer::reader
FrameworkInferencerPtr MassInferencer::inferencer
std::string MassInferencer::resultsPath
bool MassInferencer::debug
bool MassInferencer::saveOutput
int MassInferencer::alreadyProcessed
bool* MassInferencer::stopDeployer
double* MassInferencer::confidence_threshold
double MassInferencer::default_confidence_threshold
MassInferencer::MassInferencer(DatasetReaderPtr reader, FrameworkInferencerPtr inferencer, const std::string &resultsPath, double *confidence_threshold=NULL, bool debug=true)
References loadImage.path.
MassInferencer::MassInferencer(DatasetReaderPtr reader, FrameworkInferencerPtr inferencer, const std::string &resultsPath, bool debug=true)
MassInferencer::MassInferencer(DatasetReaderPtr reader, FrameworkInferencerPtr inferencer, const std::string &resultsPath, bool *stopDeployer, double *confidence_threshold=NULL, bool debug=true)
References loadImage.path.
MassInferencer::MassInferencer(DatasetReaderPtr reader, FrameworkInferencerPtr inferencer, double *confidence_threshold=NULL, bool debug=true)
MassInferencer::MassInferencer(DatasetReaderPtr reader, FrameworkInferencerPtr inferencer, bool debug=true)
void MassInferencer::process(bool writeImages, DatasetReaderPtr readerDetection=NULL)
References Sample::getSampleID, Sample::getDepthColorMapImage, Sample::getColorImage, Sample::setSampleID, Sample::save, Sample::getSampledColorImage, Sample::setColorImage, Sample::getSampledDepthColorMapImage, Sample::clearColorImage, Sample::clearDepthImage.
Referenced by SampleGeneratorHandler::Deployer::process, SampleGeneratorHandler::Detector::process, MyApp::operator().