jderobot::DepthFilter
int jderobot::DepthFilter::type
int jderobot::DepthFilter::buffSize
std::list<cv::Mat> jderobot::DepthFilter::buffer
std::list<cv::Mat> jderobot::DepthFilter::bufferGray
int jderobot::DepthFilter::erodeSize
int jderobot::DepthFilter::threshold
std::mutex jderobot::DepthFilter::m
cv::Mat jderobot::DepthFilter::globalMeanImage
cv::Mat jderobot::DepthFilter::globalDiffImage
cv::Mat jderobot::DepthFilter::globalFirstMask
cv::Mat jderobot::DepthFilter::globalSecondMask
jderobot::DepthFilter::DepthFilter(int type, int buffSize, int erodeSize, int threshold)
jderobot::DepthFilter::DepthFilter()
jderobot::DepthFilter::~DepthFilter()
References std::split, tensorflow_detect.threshold.
void jderobot::DepthFilter::update(cv::Mat imageIn, cv::Mat &imageOut)
int jderobot::DepthFilter::getBufferSize()
void jderobot::DepthFilter::setBufferSize(int size)
int jderobot::DepthFilter::getErodeSize()
void jderobot::DepthFilter::setErodeSize(int size)
int jderobot::DepthFilter::getThreshold()
void jderobot::DepthFilter::setThreshold(int value)
void jderobot::DepthFilter::setFilterType(int value)
int jderobot::DepthFilter::getFilterType()
References clear, getMeanImage, getDiffImage, getFistMask, getSecondMask, mutex.
void jderobot::DepthFilter::clear()
Referenced by getFilterType.
void jderobot::DepthFilter::getMeanImage(cv::Mat &out)
Referenced by getFilterType.
void jderobot::DepthFilter::getDiffImage(cv::Mat &out)
Referenced by getFilterType.
void jderobot::DepthFilter::getFistMask(cv::Mat &out)
Referenced by getFilterType.
void jderobot::DepthFilter::getSecondMask(cv::Mat &out)
Referenced by getFilterType.
void jderobot::DepthFilter::filterMeanNonZero(cv::Mat imageIn, cv::Mat &imageOut)
void jderobot::DepthFilter::filterDakkak(cv::Mat imageIn, cv::Mat &imageOut)
void jderobot::DepthFilter::filterMeanNonMotion3Channels(cv::Mat imageIn, cv::Mat &imageOut)
void jderobot::DepthFilter::filterMeanNonMotion1Channels(cv::Mat imageIn, cv::Mat &imageOut)