COCODatasetReader
std::map< unsigned long int, Sample > COCODatasetReader::map_image_id
COCODatasetReader::COCODatasetReader(const std::string &path, const std::string &classNamesFile, bool imagesRequired)
References DatasetReader::classNamesFile, appendDataset.
bool COCODatasetReader::appendDataset(const std::string &datasetPath, const std::string &datasetPrefix="")
References loadImage.path, DatasetReader::classNamesFile, DatasetReader::imagesRequired, find_img_directory, Sample::setSampleID, Sample::setColorImage, Sample::setSampleDims, ClassTypeGeneric::setId, ClassType::getClassString, Sample::setRectRegions, appendSegmentationRegion, Sample::getRectRegions, Sample::getSampleID, DatasetReader::samples.
Referenced by COCODatasetReader.
bool COCODatasetReader::find_img_directory(const boost::filesystem::path &dir_path, boost::filesystem::path &path_found, std::string &img_filename)
Referenced by appendDataset.
void COCODatasetReader::appendSegmentationRegion(const rapidjson::Value &node, Sample &sample, ClassTypeGeneric typeConverter, const bool isCrowd)
References getSegmentationRegion, Sample::getSampleWidth, Sample::getSampleHeight, Sample::getRleRegions, ClassType::getClassString, Sample::setRleRegions.
Referenced by appendDataset.
RLE COCODatasetReader::fromSegmentationList(const rapidjson::Value &seg, int im_width, int im_height, int size=1)
References rleFrPoly, rlesInit, rleMerge.
Referenced by getSegmentationRegion.
RLE COCODatasetReader::getSegmentationRegion(const rapidjson::Value &seg, int im_width, int im_height)
References fromSegmentationList, fromSegmentationObject.
Referenced by appendSegmentationRegion.
RLE COCODatasetReader::fromSegmentationObject(const rapidjson::Value &seg, int size=1)
References fromUncompressedRle, fromRle, rlesInit, rleMerge, rlesFree.
Referenced by getSegmentationRegion.
RLE COCODatasetReader::fromUncompressedRle(const rapidjson::Value &seg)
References rleInit.
Referenced by fromSegmentationObject.
RLE COCODatasetReader::fromRle(const rapidjson::Value &seg)
References rleFrString.
Referenced by fromSegmentationObject.