DatasetReader
std::vector<Sample> DatasetReader::samples
Referenced by COCODatasetReader::appendDataset, filterSamplesByID, getNumberOfElements, getNextSample, getNextSamples, getSampleBySampleID, printDatasetStats, addSample, ImageNetDatasetReader::appendDataset, OwnDatasetReader::appendDataset, PascalVOCDatasetReader::appendDataset, PrincetonDatasetReader::appendDataset, SamplesReader::SamplesReader, SpinelloDatasetReader::appendDataset, YoloDatasetReader::appendDataset.
int DatasetReader::readerCounter
Referenced by resetReaderCounter, decrementReaderCounter, incrementReaderCounter, getNextSample, getNextSamples.
std::string DatasetReader::classNamesFile
Referenced by COCODatasetReader::COCODatasetReader, COCODatasetReader::appendDataset, getClassNamesFile, ImageNetDatasetReader::ImageNetDatasetReader, OwnDatasetReader::OwnDatasetReader, PascalVOCDatasetReader::PascalVOCDatasetReader, PrincetonDatasetReader::PrincetonDatasetReader, SamplesReader::SamplesReader, SpinelloDatasetReader::SpinelloDatasetReader, YoloDatasetReader::YoloDatasetReader, YoloDatasetReader::appendDataset.
std::vector<std::string> DatasetReader::classNames
bool DatasetReader::imagesRequired
Referenced by COCODatasetReader::appendDataset, addSample, ImageNetDatasetReader::appendDataset, PascalVOCDatasetReader::appendDataset.
unsigned int DatasetReader::skip_count
DatasetReader::DatasetReader(const bool imagesRequired)
bool DatasetReader::getNextSample(Sample &sample)
References readerCounter, samples.
bool DatasetReader::getNextSamples(std::vector< Sample > &samples, int size)
References readerCounter, samples.
void DatasetReader::filterSamplesByID(std::vector< std::string > filteredIDS)
References samples, Sample::filterSamplesByID.
void DatasetReader::overWriteClasses(const std::string &from, const std::string &to)
int DatasetReader::getNumberOfElements()
References samples.
Referenced by printDatasetStats.
void DatasetReader::resetReaderCounter()
References readerCounter.
void DatasetReader::decrementReaderCounter(const int decrement_by=1)
References readerCounter.
void DatasetReader::incrementReaderCounter(const int increment_by=1)
References readerCounter.
bool DatasetReader::getSampleBySampleID(Sample **sample, const std::string &sampleID)
References samples.
Referenced by SpinelloDatasetReader::appendDataset.
bool DatasetReader::getSampleBySampleID(Sample **sample, const long long int sampleID)
References samples.
void DatasetReader::printDatasetStats()
References samples, getNumberOfElements.
Referenced by ImageNetDatasetReader::appendDataset, OwnDatasetReader::appendDataset, PascalVOCDatasetReader::appendDataset, PrincetonDatasetReader::appendDataset, SpinelloDatasetReader::appendDataset, YoloDatasetReader::appendDataset.
bool DatasetReader::appendDataset(const std::string &datasetPath, const std::string &datasetPrefix="")
void DatasetReader::addSample(Sample sample)
References imagesRequired, Sample::getColorImage, Sample::getDepthImage, samples.
std::string DatasetReader::getClassNamesFile()
References classNamesFile.
DatasetReader::~DatasetReader()