SampleGenerationApp
Config::Properties SampleGenerationApp::config
Referenced by MyApp::operator(), SampleGenerationApp, verifyRequirements, getConfig.
std::string SampleGenerationApp::configFilePath
Referenced by SampleGenerationApp.
std::vector<std::string> SampleGenerationApp::requiredArguments
Referenced by MyApp::MyApp, verifyRequirements.
int SampleGenerationApp::argc
Referenced by MyApp::operator().
char** SampleGenerationApp::argv
Referenced by MyApp::operator().
SampleGenerationApp::SampleGenerationApp(int argc, char *argv[])
References parse_arguments, configFilePath, config, jderobotconfig::loader::load.
virtual void SampleGenerationApp::operator()()=0
void SampleGenerationApp::process()
References verifyRequirements.
Referenced by main.
Config::Properties SampleGenerationApp::getConfig()
References config.
Referenced by MainWindow::~MainWindow.
bool SampleGenerationApp::verifyRequirements()
References config, Config::Properties::showConfig, requiredArguments, Config::Properties::keyExists.
Referenced by process.
int SampleGenerationApp::parse_arguments(const int argc, char *argv[], std::string &configFile)
Referenced by SampleGenerationApp.