maskApi.cpp
uint umin(uint a, uint b)
Referenced by rleMerge, rleIou, rleToBbox.
uint umax(uint a, uint b)
Referenced by rleToBbox, rleFrPoly.
void rleInit(RLE *R, siz h, siz w, siz m, uint *cnts)
References RLE::h, RLE::w, RLE::m, RLE::cnts.
Referenced by COCODatasetReader::fromUncompressedRle, rlesInit, rleEncode, rleMerge, rleFrPoly, rleFrString.
void rleFree(RLE *R)
References RLE::cnts.
Referenced by rlesFree, rleMerge.
void rlesInit(RLE **R, siz n)
References rleInit.
Referenced by COCODatasetReader::fromSegmentationObject, COCODatasetReader::fromSegmentationList.
void rlesFree(RLE **R, siz n)
References rleFree.
Referenced by COCODatasetReader::fromSegmentationObject.
void rleEncode(RLE *R, const byte *M, siz h, siz w, siz n)
References rleInit.
Referenced by TensorFlowInferencer::output_result.
void rleDecode(const RLE *R, byte *M, siz n)
References RLE::m, RLE::cnts.
Referenced by RleRegions::drawRegions.
void rleMerge(const RLE *R, RLE *M, siz n, int intersect)
References RLE::h, RLE::w, RLE::m, rleInit, RLE::cnts, umin, rleFree.
Referenced by COCODatasetReader::fromSegmentationObject, COCODatasetReader::fromSegmentationList.
void rleArea(const RLE *R, siz n, uint *a)
References RLE::m.
Referenced by rleIou.
void rleIou(RLE *dt, RLE *gt, siz m, siz n, byte *iscrowd, double *o)
References rleToBbox, bbIou, RLE::cnts, RLE::m, umin, rleArea.
Referenced by rleNms, StatsUtils::computeIOUMatrix.
void rleNms(RLE *dt, siz n, uint *keep, double thr)
References rleIou.
void bbIou(BB dt, BB gt, siz m, siz n, byte *iscrowd, double *o)
Referenced by rleIou, bbNms.
void bbNms(BB dt, siz n, uint *keep, double thr)
References bbIou.
void rleToBbox(const RLE *R, BB bb, siz n)
References RLE::m, RLE::cnts, umin, umax.
Referenced by rleIou.
void rleFrBbox(RLE *R, const BB bb, siz h, siz w, siz n)
References rleFrPoly.
int uintCompare(const void *a, const void *b)
Referenced by rleFrPoly.
void rleFrPoly(RLE *R, const double *xy, siz k, siz h, siz w)
References umax, uintCompare, rleInit.
Referenced by COCODatasetReader::fromSegmentationList, rleFrBbox.
char* rleToString(const RLE *R)
References RLE::m, RLE::cnts.
Referenced by COCODatasetWriter::process.
void rleFrString(RLE *R, char *s, siz h, siz w)
References rleInit.
Referenced by COCODatasetReader::fromRle.