jderobotconfig::loader
const std::string jderobotconfig::loader::CONFIG_PATH_NAME
Referenced by findConfigFile.
std::string jderobotconfig::loader::findConfigFile(const std::string &filename)
Find filename into all defined search paths. Order is:
current dirjderobot paths (*) empty if file was not found.
References std::fileexists, getEnvironmentVariable, CONFIG_PATH_NAME, loadImage.path, std::split.
Referenced by load.
Config::Properties jderobotconfig::loader::load(std::string filename)
Loads File configuration from passed file.
new Config::Config or passed one.
References findConfigFile.
Referenced by SampleGenerationApp::SampleGenerationApp, Config::load.