Comm
float Comm::PI
int Comm::MAXRANGEIMGD
CameraClient * Comm::getCameraClient(Comm::Communicator *jdrc, std::string prefix)
make a CameraClient using propierties
communicator that contains properties prefix of client Propierties (example: "carViz.Camera") null if propierties are wrong
References Comm::Communicator::getConfig, Config::Properties::asString, server2int, Config::Properties::asStringWithDefault, Comm::ListenerCamera::start.
Referenced by JderobotReader::JderobotReader.
JdeRobotTypes::Image Comm::translate_image_messages(const sensor_msgs::ImageConstPtr &image_msg)
translate ROS Image messages to JdeRobot Image
ROS Image Message Image translated from ROS Message
References JdeRobotTypes::Image::timeStamp, JdeRobotTypes::Image::format, JdeRobotTypes::Image::width, JdeRobotTypes::Image::height, depthToRGB, JdeRobotTypes::Image::data.
Referenced by Comm::ListenerCamera::stop.
JdeRobotTypes::Rgbd Comm::translate_rgbd(const sensor_msgs::ImageConstPtr &rgb, const sensor_msgs::ImageConstPtr &d)
translate ROS images messages to JdeRobot Rgbd
ROS Image Message ROS Image Message Rgbd translated from ROS Messages
void Comm::depthToRGB(const cv::Mat &float_img, cv::Mat &rgb_img)
Translates from 32FC1 Image format to RGB. Inf values are represented by NaN, when converting to RGB, NaN passed to 0.
ROS Image Message Image translated from ROS Message
Referenced by translate_image_messages.
int Comm::server2int(std::string server)
Referenced by getCameraClient.
void Comm::depthToRGB(const cv::Mat &float_img, cv::Mat &rgb_img, std::string type)