ClassTypeGeneric
ClassTypeGeneric::ClassTypeGeneric(const std::string &classesFile)
References fillStringClassesVector.
ClassTypeGeneric::ClassTypeGeneric(const std::string &classesFile, int id)
References fillStringClassesVector, ClassType::classID, ClassType::classes.
void ClassTypeGeneric::setId(int id)
References ClassType::classID, ClassType::classes.
Referenced by COCODatasetReader::appendDataset, YoloDatasetReader::appendDataset, CaffeInferencer::detectImp, DarknetInferencer::detectImp, KerasInferencer::detectImp, TensorFlowInferencer::detectImp.
void ClassTypeGeneric::fillStringClassesVector(const std::string &classesFile)
References ClassType::classes.
Referenced by ClassTypeGeneric.