Regions
Regions::Regions()
References saveJson, drawRegions, filterSamplesByID, empty, print.
virtual void Regions::saveJson(const std::string &outPath)=0
Referenced by Regions.
virtual void Regions::drawRegions(cv::Mat &image)=0
Referenced by Regions.
virtual void Regions::filterSamplesByID(std::vector< std::string > filteredIDS)=0
Referenced by Regions.
virtual bool Regions::empty()=0
Referenced by Regions.
virtual void Regions::print()=0
Referenced by Regions.