ClassType
std::vector<std::string> ClassType::classes
Referenced by getColor, getClassID, getAllAvailableClasses, ClassTypeGeneric::ClassTypeGeneric, ClassTypeGeneric::fillStringClassesVector, ClassTypeGeneric::setId, ClassTypeMapper::fillStringClassesVector, ClassTypeMapper::mapString, ClassTypeOwn::ClassTypeOwn, ClassTypeOwn::fillStringClassesVector.
std::string ClassType::classID
Referenced by getColor, getClassString, getClassID, ClassTypeGeneric::ClassTypeGeneric, ClassTypeGeneric::setId, ClassTypeMapper::mapString, ClassTypeOwn::ClassTypeOwn.
cv::Scalar ClassType::getColor()
References classes, classID, loadImage.red, _get_color.
Referenced by RectRegions::drawRegions.
std::string ClassType::getClassString()
References classID.
Referenced by COCODatasetReader::appendDataset, COCODatasetReader::appendSegmentationRegion, YoloDatasetReader::appendDataset, COCODatasetWriter::process, PascalVOCDatasetWriter::process, CaffeInferencer::detectImp, DarknetInferencer::detectImp, KerasInferencer::detectImp, TensorFlowInferencer::detectImp, RectRegions::drawRegions.
int ClassType::getClassID()
References classes, classID.
Referenced by COCODatasetWriter::process, YoloDatasetWriter::process.
std::vector< std::string > ClassType::getAllAvailableClasses()
References classes.
float ClassType::_get_color(int c, int x, int max)
References colorsClass.
Referenced by getColor.