Sample
RectRegionsPtr Sample::rectRegions
ContourRegionsPtr Sample::contourRegions
RleRegionsPtr Sample::rleRegions
cv::Mat Sample::colorImage
std::string Sample::colorImagePath
cv::Mat Sample::depthImage
std::string Sample::depthImagePath
std::string Sample::sampleID
int Sample::width
int Sample::height
Sample::Sample(const std::string &path, const std::string &id, bool loadDepth=true)
References loadImage.path.
Sample::Sample()
Sample::Sample(const cv::Mat &colorImage)
Sample::Sample(const cv::Mat &colorImage, const RectRegionsPtr &rectRegions)
References setColorImage, setRectRegions.
Sample::Sample(const cv::Mat &colorImage, const ContourRegionsPtr &contourRegions)
References setColorImage, setContourRegions.
Sample::Sample(const cv::Mat &colorImage, const RectRegionsPtr &rectRegions, const ContourRegionsPtr &contourRegions)
References setColorImage, setRectRegions, setContourRegions.
Sample::Sample(const cv::Mat &colorImage, const cv::Mat &depthImage, const RectRegionsPtr &rectRegions)
References setColorImage, setDepthImage, setRectRegions.
Sample::Sample(const cv::Mat &colorImage, const cv::Mat &depthImage, const ContourRegionsPtr &contourRegions)
References setColorImage, setDepthImage, setContourRegions.
Sample::Sample(const cv::Mat &colorImage, const cv::Mat &depthImage, const RectRegionsPtr &rectRegions, const ContourRegionsPtr &contourRegions)
References setColorImage, setDepthImage, setRectRegions, setContourRegions.
Sample::~Sample()
void Sample::setSampleDims(const int width, const int height)
Referenced by COCODatasetReader::appendDataset.
void Sample::setColorImage(const std::string &imagePath)
Referenced by Sample, CameraReader::getNextSample, JderobotReader::getNextSample, RecorderReader::getNextSample, VideoReader::getNextSample, COCODatasetReader::appendDataset, PrincetonDatasetReader::appendDataset, SpinelloDatasetReader::appendDataset, YoloDatasetReader::appendDataset, CaffeInferencer::detectImp, DarknetInferencer::detectImp, DetectionsEvaluator::evaluate, KerasInferencer::detectImp, MassBatchInferencer::process, MassInferencer::process, TensorFlowInferencer::detectImp, MyApp::operator().
void Sample::setColorImage(const cv::Mat &image)
void Sample::setDepthImage(const cv::Mat &image)
Referenced by Sample, RecorderReader::getNextSample, PrincetonDatasetReader::appendDataset, SpinelloDatasetReader::appendDataset, MyApp::operator().
void Sample::setDepthImage(const std::string &imagePath)
void Sample::setRectRegions(const RectRegionsPtr &regions)
Referenced by Sample, COCODatasetReader::appendDataset, SpinelloDatasetReader::appendDataset, YoloDatasetReader::appendDataset, CaffeInferencer::detectImp, DarknetInferencer::detectImp, KerasInferencer::detectImp, TensorFlowInferencer::detectImp.
void Sample::setContourRegions(const ContourRegionsPtr &regions)
Referenced by Sample.
void Sample::setRleRegions(const RleRegionsPtr &regions)
Referenced by COCODatasetReader::appendSegmentationRegion, TensorFlowInferencer::detectImp.
void Sample::setSampleID(const std::string &sampleID)
Referenced by CameraReader::getNextSample, JderobotReader::getNextSample, VideoReader::getNextSample, COCODatasetReader::appendDataset, ImageNetDatasetReader::appendDataset, OwnDatasetReader::appendDataset, PascalVOCDatasetReader::appendDataset, SpinelloDatasetReader::appendDataset, YoloDatasetReader::appendDataset, DetectionsEvaluator::evaluate, MassBatchInferencer::process, MassInferencer::process.
void Sample::clearColorImage()
Referenced by MassBatchInferencer::process, MassInferencer::process.
void Sample::clearDepthImage()
Referenced by MassBatchInferencer::process, MassInferencer::process.
int Sample::getSampleWidth() const
References getColorImage, getDepthImage.
Referenced by COCODatasetReader::appendSegmentationRegion, COCODatasetWriter::process.
int Sample::getSampleHeight() const
References getColorImage, getDepthImage.
Referenced by COCODatasetReader::appendSegmentationRegion, COCODatasetWriter::process.
RectRegionsPtr Sample::getRectRegions() const
Referenced by SampleGeneratorHandler::Viewer::process, MyApp::operator(), COCODatasetReader::appendDataset, SpinelloDatasetReader::appendDataset, COCODatasetWriter::process, PascalVOCDatasetWriter::process, YoloDatasetWriter::process, DetectionsEvaluator::evaluate, DetectionsValidator::validate, StatsUtils::computeIOUMatrix.
ContourRegionsPtr Sample::getContourRegions() const
RleRegionsPtr Sample::getRleRegions() const
Referenced by COCODatasetReader::appendSegmentationRegion, COCODatasetWriter::process, DetectionsEvaluator::evaluate, StatsUtils::computeIOUMatrix.
std::string Sample::getColorImagePath() const
Referenced by DetectionsEvaluator::evaluate.
std::string Sample::getDepthImagePath() const
cv::Mat Sample::getColorImage() const
Referenced by getSampleWidth, getSampleHeight, getSampledColorImage, DatasetReader::addSample, COCODatasetWriter::process, PascalVOCDatasetWriter::process, YoloDatasetWriter::process, MassBatchInferencer::process, MassInferencer::process, DetectionsValidator::validate, MyApp::operator().
cv::Mat Sample::getDepthImage() const
Referenced by getSampleWidth, getSampleHeight, getSampledDepthImage, getDeptImageGrayRGB, getDepthColorMapImage, DatasetReader::addSample, COCODatasetWriter::process, PascalVOCDatasetWriter::process, YoloDatasetWriter::process, DetectionsValidator::validate, MyApp::operator().
cv::Mat Sample::getDeptImageGrayRGB() const
References getDepthImage, std::split.
cv::Mat Sample::getSampledColorImage() const
References getColorImage.
Referenced by MyApp::operator(), show, MassBatchInferencer::process, MassInferencer::process.
cv::Mat Sample::getSampledDepthImage() const
References getDepthImage.
cv::Mat Sample::getSampledDepthColorMapImage(double alpha=1, double beta=0) const
References getDepthColorMapImage.
Referenced by show, MassBatchInferencer::process, MassInferencer::process.
cv::Mat Sample::getDepthColorMapImage(double alpha=1, double beta=0) const
References getDepthImage, tensorflow_detect.threshold.
Referenced by getSampledDepthColorMapImage, MassBatchInferencer::process, MassInferencer::process.
void Sample::save(const std::string &outPath, int id)
Referenced by save, OwnDatasetWriter::process, MassBatchInferencer::process, MassInferencer::process, DetectionsValidator::validate.
void Sample::save(const std::string &outPath, const std::string &filename)
References loadImage.path.
void Sample::save(const std::string &outPath)
References save.
void Sample::print()
bool Sample::show(const std::string readerImplementation, const std::string windowName, const int waitKey, const bool showDepth)
References getSampledColorImage, isDepthImageValid, getSampledDepthColorMapImage.
Referenced by SampleGeneratorHandler::Viewer::process.
bool Sample::isDepthImageValid()
Referenced by show.
bool Sample::isValid()
void Sample::filterSamplesByID(std::vector< std::string > filteredIDS)
Referenced by DatasetReader::filterSamplesByID.
std::string Sample::getSampleID()
Referenced by COCODatasetReader::appendDataset, COCODatasetWriter::process, PascalVOCDatasetWriter::process, DetectionsEvaluator::evaluate, MassBatchInferencer::process, MassInferencer::process.