ClassTypeMapper
Tree ClassTypeMapper::root
ClassTypeMapper::ClassTypeMapper(const std::string &classNamesFile)
References fillStringClassesVector.
ClassTypeMapper::ClassTypeMapper()
void ClassTypeMapper::fillStringClassesVector(const std::string &classesFile)
References ClassType::classes.
Referenced by ClassTypeMapper.
bool ClassTypeMapper::mapString(std::string &className)
References ClassType::classes, ClassType::classID, Tree::getImmediateSynonmys.
Referenced by mapFile, COCODatasetWriter::process, PascalVOCDatasetWriter::process.
std::unordered_map< std::string, std::string > ClassTypeMapper::mapFile(std::string classNamesFile)
References mapString.