ClassStatistics
std::string ClassStatistics::classID
int ClassStatistics::numGroundTruthsReg
Referenced by getRecallArray, GlobalStats::addGroundTruth.
int ClassStatistics::numGroundTruthsIg
Referenced by GlobalStats::addGroundTruth.
std::vector<double> ClassStatistics::iou
Referenced by getMeanIOU, GlobalStats::addIOU.
std::vector<int> ClassStatistics::truePositives
Referenced by getPrecisionArray, getRecallArray, GlobalStats::addIgnore, GlobalStats::addTruePositive, GlobalStats::addFalsePositive.
std::vector<int> ClassStatistics::falsePositives
Referenced by getPrecisionArray, GlobalStats::addIgnore, GlobalStats::addTruePositive, GlobalStats::addFalsePositive.
std::multiset<double> ClassStatistics::confScores
Referenced by GlobalStats::addIgnore, GlobalStats::addTruePositive, GlobalStats::addFalsePositive.
int ClassStatistics::nSamples
int ClassStatistics::falseNegatives
Referenced by GlobalStats::addFalseNegative.
int ClassStatistics::trueNegatives
ClassStatistics::ClassStatistics()
ClassStatistics::ClassStatistics(const std::string &classID)
double ClassStatistics::getMeanIOU() const
References iou.
double ClassStatistics::getAveragePrecision(std::vector< double > recallThrs) const
References getPrecisionForDiffRecallThrs.
std::vector< double > ClassStatistics::getPrecisionArray() const
References truePositives, falsePositives, divide.
Referenced by getPrecisionArrayOp.
std::vector< double > ClassStatistics::getPrecisionArrayOp() const
References getPrecisionArray.
Referenced by getPrecisionForDiffRecallThrs.
std::vector< double > ClassStatistics::getPrecisionForDiffRecallThrs(std::vector< double > recallThrs) const
References getPrecisionArrayOp, getRecallArray.
Referenced by getAveragePrecision.
std::vector< double > ClassStatistics::getRecallArray() const
References truePositives, numGroundTruthsReg.
Referenced by getPrecisionForDiffRecallThrs, getRecall.
double ClassStatistics::getRecall() const
References getRecallArray.
double ClassStatistics::divide(double x, double y)
Referenced by getPrecisionArray.