//
// Created by frivas on 22/01/17.
//

#ifndef SAMPLERGENERATOR_DATASETCONVERTER_H
#define SAMPLERGENERATOR_DATASETCONVERTER_H


class DatasetConverter {
    
};


#endif //SAMPLERGENERATOR_DATASETCONVERTER_H
