.TH "DeepLearningSuite/DeepLearningSuiteLib/FrameworkEvaluator Directory Reference" 3 "Sat Dec 15 2018" "Version 1.00" "dl-DetectionSuite" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DeepLearningSuite/DeepLearningSuiteLib/FrameworkEvaluator Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBCaffeInferencer\&.cpp\fP"
.br
.ti -1c
.RI "file \fBCaffeInferencer\&.h\fP"
.br
.ti -1c
.RI "file \fBClassStatistics\&.cpp\fP"
.br
.ti -1c
.RI "file \fBClassStatistics\&.h\fP"
.br
.ti -1c
.RI "file \fBDarknetInferencer\&.cpp\fP"
.br
.ti -1c
.RI "file \fBDarknetInferencer\&.h\fP"
.br
.ti -1c
.RI "file \fBDetectionsEvaluator\&.cpp\fP"
.br
.ti -1c
.RI "file \fBDetectionsEvaluator\&.h\fP"
.br
.ti -1c
.RI "file \fBFrameworkInferencer\&.cpp\fP"
.br
.ti -1c
.RI "file \fBFrameworkInferencer\&.h\fP"
.br
.ti -1c
.RI "file \fBGenericInferencer\&.cpp\fP"
.br
.ti -1c
.RI "file \fBGenericInferencer\&.h\fP"
.br
.ti -1c
.RI "file \fBGlobalStats\&.cpp\fP"
.br
.ti -1c
.RI "file \fBGlobalStats\&.h\fP"
.br
.ti -1c
.RI "file \fBKerasInferencer\&.cpp\fP"
.br
.ti -1c
.RI "file \fBKerasInferencer\&.h\fP"
.br
.ti -1c
.RI "file \fBMassBatchInferencer\&.cpp\fP"
.br
.ti -1c
.RI "file \fBMassBatchInferencer\&.h\fP"
.br
.ti -1c
.RI "file \fBMassInferencer\&.cpp\fP"
.br
.ti -1c
.RI "file \fBMassInferencer\&.h\fP"
.br
.ti -1c
.RI "file \fBStatsWriter\&.cpp\fP"
.br
.ti -1c
.RI "file \fBStatsWriter\&.h\fP"
.br
.ti -1c
.RI "file \fBTensorFlowInferencer\&.cpp\fP"
.br
.ti -1c
.RI "file \fBTensorFlowInferencer\&.h\fP"
.br
.in -1c
