.TH "DeepLearningSuite/DeepLearningSuiteLib/python_modules/keras_utils/bounding_box_utils.py" 3 "Sat Dec 15 2018" "Version 1.00" "dl-DetectionSuite" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DeepLearningSuite/DeepLearningSuiteLib/python_modules/keras_utils/bounding_box_utils.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBkeras_utils\&.bounding_box_utils\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBkeras_utils\&.bounding_box_utils\&.convert_coordinates\fP (tensor, start_index, conversion)"
.br
.ti -1c
.RI "def \fBkeras_utils\&.bounding_box_utils\&.convert_coordinates2\fP (tensor, start_index, conversion)"
.br
.ti -1c
.RI "def \fBkeras_utils\&.bounding_box_utils\&.intersection_area\fP (boxes1, boxes2, coords='centroids', mode='outer_product')"
.br
.ti -1c
.RI "def \fBkeras_utils\&.bounding_box_utils\&.intersection_area_\fP (boxes1, boxes2, coords='corners', mode='outer_product')"
.br
.ti -1c
.RI "def \fBkeras_utils\&.bounding_box_utils\&.iou\fP (boxes1, boxes2, coords='centroids', mode='outer_product')"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for dl-DetectionSuite from the source code\&.
