.TH "DeepLearningSuite/DeepLearningSuiteLib/FrameworkEvaluator/CaffeInferencer.h" 3 "Sat Dec 15 2018" "Version 1.00" "dl-DetectionSuite" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DeepLearningSuite/DeepLearningSuiteLib/FrameworkEvaluator/CaffeInferencer.h
.SH SYNOPSIS
.br
.PP
\fC#include 'FrameworkInferencer\&.h'\fP
.br
\fC#include <vector>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <opencv2/dnn\&.hpp>\fP
.br
\fC#include <opencv2/imgproc\&.hpp>\fP
.br
\fC#include <opencv2/highgui\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCaffeInferencer\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef boost::shared_ptr< \fBCaffeInferencer\fP > \fBCaffeInferencerPtr\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef boost::shared_ptr<\fBCaffeInferencer\fP> \fBCaffeInferencerPtr\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for dl-DetectionSuite from the source code\&.
