.TH "CameraReader" 3 "Sat Dec 15 2018" "Version 1.00" "dl-DetectionSuite" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CameraReader
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CameraReader\&.h>\fP
.PP
Inherits \fBDatasetReader\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCameraReader\fP (const int deviceId=\-1)"
.br
.ti -1c
.RI "\fB~CameraReader\fP ()"
.br
.ti -1c
.RI "bool \fBgetNextSample\fP (\fBSample\fP &sample)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CameraReader::CameraReader (const int deviceId = \fC\-1\fP)"

.SS "CameraReader::~CameraReader ()"

.SH "Member Function Documentation"
.PP 
.SS "bool CameraReader::getNextSample (\fBSample\fP & sample)\fC [virtual]\fP"

.PP
Reimplemented from \fBDatasetReader\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for dl-DetectionSuite from the source code\&.
