.TH "ClassTypeOwn" 3 "Sat Dec 15 2018" "Version 1.00" "dl-DetectionSuite" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ClassTypeOwn
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ClassTypeOwn\&.h>\fP
.PP
Inherits \fBClassType\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBClassTypeOwn\fP (int id)"
.br
.ti -1c
.RI "\fBClassTypeOwn\fP (const std::string &\fBclassID\fP)"
.br
.ti -1c
.RI "void \fBfillStringClassesVector\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ClassTypeOwn::ClassTypeOwn (int id)"

.SS "ClassTypeOwn::ClassTypeOwn (const std::string & classID)"

.SH "Member Function Documentation"
.PP 
.SS "void ClassTypeOwn::fillStringClassesVector ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for dl-DetectionSuite from the source code\&.
