.TH "ClassTypeMapper" 3 "Sat Dec 15 2018" "Version 1.00" "dl-DetectionSuite" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ClassTypeMapper
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ClassTypeMapper\&.h>\fP
.PP
Inherits \fBClassType\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBClassTypeMapper\fP (const std::string &classNamesFile)"
.br
.ti -1c
.RI "\fBClassTypeMapper\fP ()"
.br
.ti -1c
.RI "void \fBfillStringClassesVector\fP (const std::string &classesFile)"
.br
.ti -1c
.RI "bool \fBmapString\fP (std::string &className)"
.br
.ti -1c
.RI "std::unordered_map< std::string, std::string > \fBmapFile\fP (std::string classNamesFile)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ClassTypeMapper::ClassTypeMapper (const std::string & classNamesFile)"

.SS "ClassTypeMapper::ClassTypeMapper ()"

.SH "Member Function Documentation"
.PP 
.SS "void ClassTypeMapper::fillStringClassesVector (const std::string & classesFile)"

.SS "std::unordered_map< std::string, std::string > ClassTypeMapper::mapFile (std::string classNamesFile)"

.SS "bool ClassTypeMapper::mapString (std::string & className)"


.SH "Author"
.PP 
Generated automatically by Doxygen for dl-DetectionSuite from the source code\&.
