.TH "DeepLearningSuite/DeepLearningSuiteLib/DatasetConverters/readers/COCODatasetReader.h" 3 "Sat Dec 15 2018" "Version 1.00" "dl-DetectionSuite" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DeepLearningSuite/DeepLearningSuiteLib/DatasetConverters/readers/COCODatasetReader.h
.SH SYNOPSIS
.br
.PP
\fC#include <DatasetConverters/readers/DatasetReader\&.h>\fP
.br
\fC#include <rapidjson/document\&.h>\fP
.br
\fC#include <rapidjson/prettywriter\&.h>\fP
.br
\fC#include <rapidjson/stringbuffer\&.h>\fP
.br
\fC#include 'rapidjson/error/en\&.h'\fP
.br
\fC#include <boost/filesystem/path\&.hpp>\fP
.br
\fC#include <boost/filesystem/operations\&.hpp>\fP
.br
\fC#include 'DatasetConverters/ClassTypeGeneric\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCOCODatasetReader\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef boost::shared_ptr< \fBCOCODatasetReader\fP > \fBCOCODatasetReaderPtr\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef boost::shared_ptr<\fBCOCODatasetReader\fP> \fBCOCODatasetReaderPtr\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for dl-DetectionSuite from the source code\&.
