.TH "colorspaces" 3 "Sat Dec 15 2018" "Version 1.00" "dl-DetectionSuite" \" -*- nroff -*-
.ad l
.nh
.SH NAME
colorspaces
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBImage\fP"
.br
.ti -1c
.RI "class \fBImageGRAY8\fP"
.br
.ti -1c
.RI "class \fBImageHSV8\fP"
.br
.ti -1c
.RI "class \fBImageNV21\fP"
.br
.ti -1c
.RI "class \fBImageRGB8\fP"
.br
.ti -1c
.RI "class \fBImageYCRCB\fP"
.br
.ti -1c
.RI "class \fBImageYUY2\fP"
.br
.ti -1c
.RI "class \fBUncopyable\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for dl-DetectionSuite from the source code\&.
