.TH "colorspaces::Image::FormatMismatch" 3 "Sat Dec 15 2018" "Version 1.00" "dl-DetectionSuite" \" -*- nroff -*-
.ad l
.nh
.SH NAME
colorspaces::Image::FormatMismatch
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <imagecv\&.h>\fP
.PP
Inherits exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFormatMismatch\fP (const std::string msg)"
.br
.ti -1c
.RI "\fB~FormatMismatch\fP ()  throw ()"
.br
.ti -1c
.RI "virtual const char * \fBwhat\fP () const  throw ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "colorspaces::Image::FormatMismatch::FormatMismatch (const std::string msg)\fC [inline]\fP"

.SS "colorspaces::Image::FormatMismatch::~FormatMismatch ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual const char* colorspaces::Image::FormatMismatch::what () const\fC [inline]\fP, \fC [virtual]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for dl-DetectionSuite from the source code\&.
