.TH "DeepLearningSuite/DeepLearningSuiteLib/DatasetConverters/readers/DatasetReader.h" 3 "Sat Dec 15 2018" "Version 1.00" "dl-DetectionSuite" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DeepLearningSuite/DeepLearningSuiteLib/DatasetConverters/readers/DatasetReader.h
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <Common/Sample\&.h>\fP
.br
\fC#include <boost/shared_ptr\&.hpp>\fP
.br
\fC#include <Common/EvalMatrix\&.h>\fP
.br
\fC#include <glog/logging\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDatasetReader\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef boost::shared_ptr< \fBDatasetReader\fP > \fBDatasetReaderPtr\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef boost::shared_ptr<\fBDatasetReader\fP> \fBDatasetReaderPtr\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for dl-DetectionSuite from the source code\&.
