.TH "DepthUtils" 3 "Sat Dec 15 2018" "Version 1.00" "dl-DetectionSuite" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DepthUtils
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DepthUtils\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmat16_to_ownFormat\fP (const cv::Mat &inputImage, cv::Mat &outImage)"
.br
.ti -1c
.RI "static void \fBspinello_mat16_to_viewable\fP (const cv::Mat &inputImage, cv::Mat &outImage)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void DepthUtils::mat16_to_ownFormat (const cv::Mat & inputImage, cv::Mat & outImage)\fC [static]\fP"

.SS "void DepthUtils::spinello_mat16_to_viewable (const cv::Mat & inputImage, cv::Mat & outImage)\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for dl-DetectionSuite from the source code\&.
