.TH "Detector" 3 "Sat Dec 15 2018" "Version 1.00" "dl-DetectionSuite" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Detector
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Detector\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDetector\fP ()"
.br
.ti -1c
.RI "virtual \fBSample\fP \fBinferImage\fP (const cv::Mat &image)=0"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Detector::Detector ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual \fBSample\fP Detector::inferImage (const cv::Mat & image)\fC [pure virtual]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for dl-DetectionSuite from the source code\&.
