.TH "DeepLearningSuite/DatasetEvaluationApp/SamplerGeneratorHandler/Detector.cpp" 3 "Sat Dec 15 2018" "Version 1.00" "dl-DetectionSuite" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DeepLearningSuite/DatasetEvaluationApp/SamplerGeneratorHandler/Detector.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <DatasetConverters/readers/GenericDatasetReader\&.h>\fP
.br
\fC#include <DatasetConverters/writers/GenericDatasetWriter\&.h>\fP
.br
\fC#include <gui/Utils\&.h>\fP
.br
\fC#include <glog/logging\&.h>\fP
.br
\fC#include <FrameworkEvaluator/GenericInferencer\&.h>\fP
.br
\fC#include <FrameworkEvaluator/MassInferencer\&.h>\fP
.br
\fC#include 'Detector\&.h'\fP
.br
\fC#include 'SamplerGenerationHandler\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for dl-DetectionSuite from the source code\&.
