.TH "generator" 3 "Sat Dec 15 2018" "Version 1.00" "dl-DetectionSuite" \" -*- nroff -*-
.ad l
.nh
.SH NAME
generator
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBconfigure_arguments\fP ()"
.br
.ti -1c
.RI "def \fBmain\fP (path)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "def \fBargs\fP = \fBconfigure_arguments\fP()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def generator\&.configure_arguments ()"

.SS "def generator\&.main ( path)"

.SH "Variable Documentation"
.PP 
.SS "def generator\&.args = \fBconfigure_arguments\fP()"

.SH "Author"
.PP 
Generated automatically by Doxygen for dl-DetectionSuite from the source code\&.
