.TH "DeepLearningSuite/SampleGenerationApp/generator.cpp" 3 "Sat Dec 15 2018" "Version 1.00" "dl-DetectionSuite" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DeepLearningSuite/SampleGenerationApp/generator.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <random>\fP
.br
\fC#include <boost/program_options\&.hpp>\fP
.br
\fC#include <boost/filesystem\&.hpp>\fP
.br
\fC#include <opencv2/highgui/highgui\&.hpp>\fP
.br
\fC#include 'DatasetConverters/liveReaders/RecorderReader\&.h'\fP
.br
\fC#include 'GenerationUtils/DepthForegroundSegmentator\&.h'\fP
.br
\fC#include 'GenerationUtils/DetectionsValidator\&.h'\fP
.br
\fC#include <glog/logging\&.h>\fP
.br
\fC#include <Utils/SampleGenerationApp\&.h>\fP
.br
\fC#include <FrameworkEvaluator/FrameworkInferencer\&.h>\fP
.br
\fC#include <DatasetConverters/readers/GenericDatasetReader\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMyApp\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.SH "Author"
.PP 
Generated automatically by Doxygen for dl-DetectionSuite from the source code\&.
