.TH "datasetGenerator/generator.py" 3 "Sat Dec 15 2018" "Version 1.00" "dl-DetectionSuite" \" -*- nroff -*-
.ad l
.nh
.SH NAME
datasetGenerator/generator.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBgenerator\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBgenerator\&.configure_arguments\fP ()"
.br
.ti -1c
.RI "def \fBgenerator\&.main\fP (path)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "def \fBgenerator\&.args\fP = configure_arguments()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for dl-DetectionSuite from the source code\&.
