.TH "GenericDatasetWriter" 3 "Sat Dec 15 2018" "Version 1.00" "dl-DetectionSuite" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GenericDatasetWriter
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GenericDatasetWriter\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGenericDatasetWriter\fP (const std::string &path, \fBDatasetReaderPtr\fP &reader, const std::string &writerImplementation, const std::string &writerNamesFile=std::string())"
.br
.ti -1c
.RI "\fBDatasetWriterPtr\fP \fBgetWriter\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static std::vector< std::string > \fBgetAvailableImplementations\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "GenericDatasetWriter::GenericDatasetWriter (const std::string & path, \fBDatasetReaderPtr\fP & reader, const std::string & writerImplementation, const std::string & writerNamesFile = \fCstd::string()\fP)"

.SH "Member Function Documentation"
.PP 
.SS "std::vector< std::string > GenericDatasetWriter::getAvailableImplementations ()\fC [static]\fP"

.SS "\fBDatasetWriterPtr\fP GenericDatasetWriter::getWriter ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for dl-DetectionSuite from the source code\&.
