.TH "HSV" 3 "Sat Dec 15 2018" "Version 1.00" "dl-DetectionSuite" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HSV \- *** RGB to HSI *** ///  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <colorspaces\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBH\fP"
.br
.ti -1c
.RI "double \fBS\fP"
.br
.ti -1c
.RI "double \fBV\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
*** RGB to HSI *** /// 
.SH "Member Data Documentation"
.PP 
.SS "double HSV::H"

.SS "double HSV::S"

.SS "double HSV::V"


.SH "Author"
.PP 
Generated automatically by Doxygen for dl-DetectionSuite from the source code\&.
