.TH "jderobot" 3 "Sat Dec 15 2018" "Version 1.00" "dl-DetectionSuite" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jderobot
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDepthFilter\fP"
.br
.ti -1c
.RI "class \fBDepthSampler\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for dl-DetectionSuite from the source code\&.
