.TH "keras_detect.KerasDetector" 3 "Sat Dec 15 2018" "Version 1.00" "dl-DetectionSuite" \" -*- nroff -*-
.ad l
.nh
.SH NAME
keras_detect.KerasDetector
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, path_to_hdf5)"
.br
.ti -1c
.RI "def \fBdetect\fP (self, img, threshold)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBmodel\fP"
.br
.ti -1c
.RI "\fBimg_height\fP"
.br
.ti -1c
.RI "\fBimg_width\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def keras_detect\&.KerasDetector\&.__init__ ( self,  path_to_hdf5)"

.SH "Member Function Documentation"
.PP 
.SS "def keras_detect\&.KerasDetector\&.detect ( self,  img,  threshold)"

.SH "Member Data Documentation"
.PP 
.SS "keras_detect\&.KerasDetector\&.img_height"

.SS "keras_detect\&.KerasDetector\&.img_width"

.SS "keras_detect\&.KerasDetector\&.model"


.SH "Author"
.PP 
Generated automatically by Doxygen for dl-DetectionSuite from the source code\&.
