.TH "datasetGenerator/loadImage.py" 3 "Sat Dec 15 2018" "Version 1.00" "dl-DetectionSuite" \" -*- nroff -*-
.ad l
.nh
.SH NAME
datasetGenerator/loadImage.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBloadImage\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBloadImage\&.path\fP = '/mnt/large/pentalo/deep/external_datasets/princeton/EvaluationSet/bag1/depth/d\-0\-1\&.png'"
.br
.ti -1c
.RI "\fBloadImage\&.im\fP = Image\&.open(path)"
.br
.ti -1c
.RI "\fBloadImage\&.red\fP = im\&.getextrema()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for dl-DetectionSuite from the source code\&.
