.TH "loadImage" 3 "Sat Dec 15 2018" "Version 1.00" "dl-DetectionSuite" \" -*- nroff -*-
.ad l
.nh
.SH NAME
loadImage
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBpath\fP = '/mnt/large/pentalo/deep/external_datasets/princeton/EvaluationSet/bag1/depth/d\-0\-1\&.png'"
.br
.ti -1c
.RI "\fBim\fP = Image\&.open(\fBpath\fP)"
.br
.ti -1c
.RI "\fBred\fP = im\&.getextrema()"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "loadImage\&.im = Image\&.open(\fBpath\fP)"

.SS "string loadImage\&.path = '/mnt/large/pentalo/deep/external_datasets/princeton/EvaluationSet/bag1/depth/d\-0\-1\&.png'"

.SS "loadImage\&.red = im\&.getextrema()"

.SH "Author"
.PP 
Generated automatically by Doxygen for dl-DetectionSuite from the source code\&.
