.TH "main" 3 "Sat Dec 15 2018" "Version 1.00" "dl-DetectionSuite" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBgetIfPropertyToTest\fP (sampleNumber, testRatio)"
.br
.ti -1c
.RI "def \fBmainDepth\fP ()"
.br
.ti -1c
.RI "def \fBmaincolor\fP ()"
.br
.ti -1c
.RI "def \fBmain\fP ()"
.br
.ti -1c
.RI "def \fBmain2\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBinput_folder\fP = '/mnt/large/pentalo/\fBsample\fP/data/images/'"
.br
.ti -1c
.RI "string \fBoutput_folder\fP = '\&./out/'"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def main\&.getIfPropertyToTest ( sampleNumber,  testRatio)"

.SS "def main\&.main ()"

.SS "def main\&.main2 ()"

.SS "def main\&.maincolor ()"

.SS "def main\&.mainDepth ()"

.SH "Variable Documentation"
.PP 
.SS "string main\&.input_folder = '/mnt/large/pentalo/\fBsample\fP/data/images/'"

.SS "string main\&.output_folder = '\&./out/'"

.SH "Author"
.PP 
Generated automatically by Doxygen for dl-DetectionSuite from the source code\&.
