.TH "DeepLearningSuite/build/DatasetEvaluationApp/DatasetEvaluationApp_autogen/moc_predefs.h" 3 "Sat Dec 15 2018" "Version 1.00" "dl-DetectionSuite" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DeepLearningSuite/build/DatasetEvaluationApp/DatasetEvaluationApp_autogen/moc_predefs.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__SSP_STRONG__\fP   3"
.br
.ti -1c
.RI "#define \fB__DBL_MIN_EXP__\fP   (\-1021)"
.br
.ti -1c
.RI "#define \fB__FLT32X_MAX_EXP__\fP   1024"
.br
.ti -1c
.RI "#define \fB__cpp_attributes\fP   200809"
.br
.ti -1c
.RI "#define \fB__UINT_LEAST16_MAX__\fP   0xffff"
.br
.ti -1c
.RI "#define \fB__ATOMIC_ACQUIRE\fP   2"
.br
.ti -1c
.RI "#define \fB__FLT128_MAX_10_EXP__\fP   4932"
.br
.ti -1c
.RI "#define \fB__FLT_MIN__\fP   1\&.17549435082228750796873653722224568e\-38F"
.br
.ti -1c
.RI "#define \fB__GCC_IEC_559_COMPLEX\fP   2"
.br
.ti -1c
.RI "#define \fB__cpp_aggregate_nsdmi\fP   201304"
.br
.ti -1c
.RI "#define \fB__UINT_LEAST8_TYPE__\fP   unsigned char"
.br
.ti -1c
.RI "#define \fB__SIZEOF_FLOAT80__\fP   16"
.br
.ti -1c
.RI "#define \fB__INTMAX_C\fP(c)   c ## L"
.br
.ti -1c
.RI "#define \fB__CHAR_BIT__\fP   8"
.br
.ti -1c
.RI "#define \fB__UINT8_MAX__\fP   0xff"
.br
.ti -1c
.RI "#define \fB__WINT_MAX__\fP   0xffffffffU"
.br
.ti -1c
.RI "#define \fB__FLT32_MIN_EXP__\fP   (\-125)"
.br
.ti -1c
.RI "#define \fB__cpp_static_assert\fP   200410"
.br
.ti -1c
.RI "#define \fBQT_GUI_LIB\fP   1"
.br
.ti -1c
.RI "#define \fB__ORDER_LITTLE_ENDIAN__\fP   1234"
.br
.ti -1c
.RI "#define \fB__SIZE_MAX__\fP   0xffffffffffffffffUL"
.br
.ti -1c
.RI "#define \fB__WCHAR_MAX__\fP   0x7fffffff"
.br
.ti -1c
.RI "#define \fB__GCC_HAVE_SYNC_COMPARE_AND_SWAP_1\fP   1"
.br
.ti -1c
.RI "#define \fB__GCC_HAVE_SYNC_COMPARE_AND_SWAP_2\fP   1"
.br
.ti -1c
.RI "#define \fB__GCC_HAVE_SYNC_COMPARE_AND_SWAP_4\fP   1"
.br
.ti -1c
.RI "#define \fB__DBL_DENORM_MIN__\fP   double(4\&.94065645841246544176568792868221372e\-324L)"
.br
.ti -1c
.RI "#define \fB__GCC_HAVE_SYNC_COMPARE_AND_SWAP_8\fP   1"
.br
.ti -1c
.RI "#define \fB__GCC_ATOMIC_CHAR_LOCK_FREE\fP   2"
.br
.ti -1c
.RI "#define \fB__GCC_IEC_559\fP   2"
.br
.ti -1c
.RI "#define \fB__FLT32X_DECIMAL_DIG__\fP   17"
.br
.ti -1c
.RI "#define \fB__FLT_EVAL_METHOD__\fP   0"
.br
.ti -1c
.RI "#define \fB__unix__\fP   1"
.br
.ti -1c
.RI "#define \fB__cpp_binary_literals\fP   201304"
.br
.ti -1c
.RI "#define \fB__FLT64_DECIMAL_DIG__\fP   17"
.br
.ti -1c
.RI "#define \fB__GCC_ATOMIC_CHAR32_T_LOCK_FREE\fP   2"
.br
.ti -1c
.RI "#define \fB__x86_64\fP   1"
.br
.ti -1c
.RI "#define \fB__cpp_variadic_templates\fP   200704"
.br
.ti -1c
.RI "#define \fB__UINT_FAST64_MAX__\fP   0xffffffffffffffffUL"
.br
.ti -1c
.RI "#define \fB__SIG_ATOMIC_TYPE__\fP   int"
.br
.ti -1c
.RI "#define \fB__DBL_MIN_10_EXP__\fP   (\-307)"
.br
.ti -1c
.RI "#define \fB__FINITE_MATH_ONLY__\fP   0"
.br
.ti -1c
.RI "#define \fB__cpp_variable_templates\fP   201304"
.br
.ti -1c
.RI "#define \fBSIZEOF_DPTR\fP   (sizeof(void*))"
.br
.ti -1c
.RI "#define \fB__GNUC_PATCHLEVEL__\fP   0"
.br
.ti -1c
.RI "#define \fB__FLT32_HAS_DENORM__\fP   1"
.br
.ti -1c
.RI "#define \fB__UINT_FAST8_MAX__\fP   0xff"
.br
.ti -1c
.RI "#define \fB__has_include\fP(STR)   __has_include__(STR)"
.br
.ti -1c
.RI "#define \fB__DEC64_MAX_EXP__\fP   385"
.br
.ti -1c
.RI "#define \fB__INT8_C\fP(c)   c"
.br
.ti -1c
.RI "#define \fB__INT_LEAST8_WIDTH__\fP   8"
.br
.ti -1c
.RI "#define \fB__UINT_LEAST64_MAX__\fP   0xffffffffffffffffUL"
.br
.ti -1c
.RI "#define \fBQT_OPENGL_LIB\fP   1"
.br
.ti -1c
.RI "#define \fB__SHRT_MAX__\fP   0x7fff"
.br
.ti -1c
.RI "#define \fB__LDBL_MAX__\fP   1\&.18973149535723176502126385303097021e+4932L"
.br
.ti -1c
.RI "#define \fB__FLT64X_MAX_10_EXP__\fP   4932"
.br
.ti -1c
.RI "#define \fBQT_NO_DEBUG\fP   1"
.br
.ti -1c
.RI "#define \fB__UINT_LEAST8_MAX__\fP   0xff"
.br
.ti -1c
.RI "#define \fB__GCC_ATOMIC_BOOL_LOCK_FREE\fP   2"
.br
.ti -1c
.RI "#define \fB__FLT128_DENORM_MIN__\fP   6\&.47517511943802511092443895822764655e\-4966F128"
.br
.ti -1c
.RI "#define \fB__UINTMAX_TYPE__\fP   long unsigned int"
.br
.ti -1c
.RI "#define \fB__linux\fP   1"
.br
.ti -1c
.RI "#define \fB__DEC32_EPSILON__\fP   1E\-6DF"
.br
.ti -1c
.RI "#define \fB__FLT_EVAL_METHOD_TS_18661_3__\fP   0"
.br
.ti -1c
.RI "#define \fB__unix\fP   1"
.br
.ti -1c
.RI "#define \fB__UINT32_MAX__\fP   0xffffffffU"
.br
.ti -1c
.RI "#define \fB__GXX_EXPERIMENTAL_CXX0X__\fP   1"
.br
.ti -1c
.RI "#define \fB__LDBL_MAX_EXP__\fP   16384"
.br
.ti -1c
.RI "#define \fB__FLT128_MIN_EXP__\fP   (\-16381)"
.br
.ti -1c
.RI "#define \fB__WINT_MIN__\fP   0U"
.br
.ti -1c
.RI "#define \fB__linux__\fP   1"
.br
.ti -1c
.RI "#define \fB__FLT128_MIN_10_EXP__\fP   (\-4931)"
.br
.ti -1c
.RI "#define \fB__INT_LEAST16_WIDTH__\fP   16"
.br
.ti -1c
.RI "#define \fB__SCHAR_MAX__\fP   0x7f"
.br
.ti -1c
.RI "#define \fB__FLT128_MANT_DIG__\fP   113"
.br
.ti -1c
.RI "#define \fB__WCHAR_MIN__\fP   (\-\fB__WCHAR_MAX__\fP \- 1)"
.br
.ti -1c
.RI "#define \fBQT_SVG_LIB\fP   1"
.br
.ti -1c
.RI "#define \fB__INT64_C\fP(c)   c ## L"
.br
.ti -1c
.RI "#define \fB__DBL_DIG__\fP   15"
.br
.ti -1c
.RI "#define \fB__GCC_ATOMIC_POINTER_LOCK_FREE\fP   2"
.br
.ti -1c
.RI "#define \fB__FLT64X_MANT_DIG__\fP   64"
.br
.ti -1c
.RI "#define \fB__SIZEOF_INT__\fP   4"
.br
.ti -1c
.RI "#define \fB__SIZEOF_POINTER__\fP   8"
.br
.ti -1c
.RI "#define \fB__GCC_ATOMIC_CHAR16_T_LOCK_FREE\fP   2"
.br
.ti -1c
.RI "#define \fB__USER_LABEL_PREFIX__\fP"
.br
.ti -1c
.RI "#define \fB__FLT64X_EPSILON__\fP   1\&.08420217248550443400745280086994171e\-19F64x"
.br
.ti -1c
.RI "#define \fB__STDC_HOSTED__\fP   1"
.br
.ti -1c
.RI "#define \fB__LDBL_HAS_INFINITY__\fP   1"
.br
.ti -1c
.RI "#define \fB__FLT32_DIG__\fP   6"
.br
.ti -1c
.RI "#define \fB__FLT_EPSILON__\fP   1\&.19209289550781250000000000000000000e\-7F"
.br
.ti -1c
.RI "#define \fB__GXX_WEAK__\fP   1"
.br
.ti -1c
.RI "#define \fB__SHRT_WIDTH__\fP   16"
.br
.ti -1c
.RI "#define \fB__LDBL_MIN__\fP   3\&.36210314311209350626267781732175260e\-4932L"
.br
.ti -1c
.RI "#define \fB__DEC32_MAX__\fP   9\&.999999E96DF"
.br
.ti -1c
.RI "#define \fB__cpp_threadsafe_static_init\fP   200806"
.br
.ti -1c
.RI "#define \fB__FLT64X_DENORM_MIN__\fP   3\&.64519953188247460252840593361941982e\-4951F64x"
.br
.ti -1c
.RI "#define \fB__FLT32X_HAS_INFINITY__\fP   1"
.br
.ti -1c
.RI "#define \fB__INT32_MAX__\fP   0x7fffffff"
.br
.ti -1c
.RI "#define \fB__INT_WIDTH__\fP   32"
.br
.ti -1c
.RI "#define \fB__SIZEOF_LONG__\fP   8"
.br
.ti -1c
.RI "#define \fB__STDC_IEC_559__\fP   1"
.br
.ti -1c
.RI "#define \fB__STDC_ISO_10646__\fP   201706L"
.br
.ti -1c
.RI "#define \fB__UINT16_C\fP(c)   c"
.br
.ti -1c
.RI "#define \fB__PTRDIFF_WIDTH__\fP   64"
.br
.ti -1c
.RI "#define \fB__DECIMAL_DIG__\fP   21"
.br
.ti -1c
.RI "#define \fB__FLT64_EPSILON__\fP   2\&.22044604925031308084726333618164062e\-16F64"
.br
.ti -1c
.RI "#define \fB__gnu_linux__\fP   1"
.br
.ti -1c
.RI "#define \fB__INTMAX_WIDTH__\fP   64"
.br
.ti -1c
.RI "#define \fB__FLT64_MIN_EXP__\fP   (\-1021)"
.br
.ti -1c
.RI "#define \fB__has_include_next\fP(STR)   __has_include_next__(STR)"
.br
.ti -1c
.RI "#define \fB__FLT64X_MIN_10_EXP__\fP   (\-4931)"
.br
.ti -1c
.RI "#define \fB__LDBL_HAS_QUIET_NAN__\fP   1"
.br
.ti -1c
.RI "#define \fB__FLT64_MANT_DIG__\fP   53"
.br
.ti -1c
.RI "#define \fB__GNUC__\fP   7"
.br
.ti -1c
.RI "#define \fB__GXX_RTTI\fP   1"
.br
.ti -1c
.RI "#define \fB__pie__\fP   2"
.br
.ti -1c
.RI "#define \fB__MMX__\fP   1"
.br
.ti -1c
.RI "#define \fB__cpp_delegating_constructors\fP   200604"
.br
.ti -1c
.RI "#define \fB__FLT_HAS_DENORM__\fP   1"
.br
.ti -1c
.RI "#define \fB__SIZEOF_LONG_DOUBLE__\fP   16"
.br
.ti -1c
.RI "#define \fB__BIGGEST_ALIGNMENT__\fP   16"
.br
.ti -1c
.RI "#define \fB__STDC_UTF_16__\fP   1"
.br
.ti -1c
.RI "#define \fB__FLT64_MAX_10_EXP__\fP   308"
.br
.ti -1c
.RI "#define \fB__FLT32_HAS_INFINITY__\fP   1"
.br
.ti -1c
.RI "#define \fB__DBL_MAX__\fP   double(1\&.79769313486231570814527423731704357e+308L)"
.br
.ti -1c
.RI "#define \fB__cpp_raw_strings\fP   200710"
.br
.ti -1c
.RI "#define \fB__INT_FAST32_MAX__\fP   0x7fffffffffffffffL"
.br
.ti -1c
.RI "#define \fB__DBL_HAS_INFINITY__\fP   1"
.br
.ti -1c
.RI "#define \fB__INT64_MAX__\fP   0x7fffffffffffffffL"
.br
.ti -1c
.RI "#define \fB__DEC32_MIN_EXP__\fP   (\-94)"
.br
.ti -1c
.RI "#define \fB__INTPTR_WIDTH__\fP   64"
.br
.ti -1c
.RI "#define \fB__FLT32X_HAS_DENORM__\fP   1"
.br
.ti -1c
.RI "#define \fB__INT_FAST16_TYPE__\fP   long int"
.br
.ti -1c
.RI "#define \fB__LDBL_HAS_DENORM__\fP   1"
.br
.ti -1c
.RI "#define \fBQT_WIDGETS_LIB\fP   1"
.br
.ti -1c
.RI "#define \fB__cplusplus\fP   201402L"
.br
.ti -1c
.RI "#define \fB__cpp_ref_qualifiers\fP   200710"
.br
.ti -1c
.RI "#define \fB__DEC128_MAX__\fP   9\&.999999999999999999999999999999999E6144DL"
.br
.ti -1c
.RI "#define \fB__INT_LEAST32_MAX__\fP   0x7fffffff"
.br
.ti -1c
.RI "#define \fB__DEC32_MIN__\fP   1E\-95DF"
.br
.ti -1c
.RI "#define \fB__DEPRECATED\fP   1"
.br
.ti -1c
.RI "#define \fB__cpp_rvalue_references\fP   200610"
.br
.ti -1c
.RI "#define \fB__DBL_MAX_EXP__\fP   1024"
.br
.ti -1c
.RI "#define \fB__WCHAR_WIDTH__\fP   32"
.br
.ti -1c
.RI "#define \fB__FLT32_MAX__\fP   3\&.40282346638528859811704183484516925e+38F32"
.br
.ti -1c
.RI "#define \fB__DEC128_EPSILON__\fP   1E\-33DL"
.br
.ti -1c
.RI "#define \fB__SSE2_MATH__\fP   1"
.br
.ti -1c
.RI "#define \fB__ATOMIC_HLE_RELEASE\fP   131072"
.br
.ti -1c
.RI "#define \fB__PTRDIFF_MAX__\fP   0x7fffffffffffffffL"
.br
.ti -1c
.RI "#define \fB__amd64\fP   1"
.br
.ti -1c
.RI "#define \fB__STDC_NO_THREADS__\fP   1"
.br
.ti -1c
.RI "#define \fB__ATOMIC_HLE_ACQUIRE\fP   65536"
.br
.ti -1c
.RI "#define \fB__FLT32_HAS_QUIET_NAN__\fP   1"
.br
.ti -1c
.RI "#define \fB__GNUG__\fP   7"
.br
.ti -1c
.RI "#define \fB__LONG_LONG_MAX__\fP   0x7fffffffffffffffLL"
.br
.ti -1c
.RI "#define \fB__SIZEOF_SIZE_T__\fP   8"
.br
.ti -1c
.RI "#define \fB__cpp_rvalue_reference\fP   200610"
.br
.ti -1c
.RI "#define \fB__cpp_nsdmi\fP   200809"
.br
.ti -1c
.RI "#define \fB__FLT64X_MIN_EXP__\fP   (\-16381)"
.br
.ti -1c
.RI "#define \fB__SIZEOF_WINT_T__\fP   4"
.br
.ti -1c
.RI "#define \fB__LONG_LONG_WIDTH__\fP   64"
.br
.ti -1c
.RI "#define \fB__cpp_initializer_lists\fP   200806"
.br
.ti -1c
.RI "#define \fB__FLT32_MAX_EXP__\fP   128"
.br
.ti -1c
.RI "#define \fBABI_ID\fP   'ELF'"
.br
.ti -1c
.RI "#define \fB__cpp_hex_float\fP   201603"
.br
.ti -1c
.RI "#define \fB__GCC_HAVE_DWARF2_CFI_ASM\fP   1"
.br
.ti -1c
.RI "#define \fB__GXX_ABI_VERSION\fP   1011"
.br
.ti -1c
.RI "#define \fB__FLT128_HAS_INFINITY__\fP   1"
.br
.ti -1c
.RI "#define \fB__FLT_MIN_EXP__\fP   (\-125)"
.br
.ti -1c
.RI "#define \fB__cpp_lambdas\fP   200907"
.br
.ti -1c
.RI "#define \fB__FLT64X_HAS_QUIET_NAN__\fP   1"
.br
.ti -1c
.RI "#define \fB__INT_FAST64_TYPE__\fP   long int"
.br
.ti -1c
.RI "#define \fB__FLT64_DENORM_MIN__\fP   4\&.94065645841246544176568792868221372e\-324F64"
.br
.ti -1c
.RI "#define \fB__DBL_MIN__\fP   double(2\&.22507385850720138309023271733240406e\-308L)"
.br
.ti -1c
.RI "#define \fB__PIE__\fP   2"
.br
.ti -1c
.RI "#define \fB__LP64__\fP   1"
.br
.ti -1c
.RI "#define \fB__FLT32X_EPSILON__\fP   2\&.22044604925031308084726333618164062e\-16F32x"
.br
.ti -1c
.RI "#define \fB__DECIMAL_BID_FORMAT__\fP   1"
.br
.ti -1c
.RI "#define \fB__FLT64_MIN_10_EXP__\fP   (\-307)"
.br
.ti -1c
.RI "#define \fB__FLT64X_DECIMAL_DIG__\fP   21"
.br
.ti -1c
.RI "#define \fB__DEC128_MIN__\fP   1E\-6143DL"
.br
.ti -1c
.RI "#define \fB__REGISTER_PREFIX__\fP"
.br
.ti -1c
.RI "#define \fB__UINT16_MAX__\fP   0xffff"
.br
.ti -1c
.RI "#define \fB__DBL_HAS_DENORM__\fP   1"
.br
.ti -1c
.RI "#define \fB__FLT32_MIN__\fP   1\&.17549435082228750796873653722224568e\-38F32"
.br
.ti -1c
.RI "#define \fB__UINT8_TYPE__\fP   unsigned char"
.br
.ti -1c
.RI "#define \fB__NO_INLINE__\fP   1"
.br
.ti -1c
.RI "#define \fB__FLT_MANT_DIG__\fP   24"
.br
.ti -1c
.RI "#define \fB__LDBL_DECIMAL_DIG__\fP   21"
.br
.ti -1c
.RI "#define \fB__VERSION__\fP   '7\&.3\&.0'"
.br
.ti -1c
.RI "#define \fB__UINT64_C\fP(c)   c ## UL"
.br
.ti -1c
.RI "#define \fB__cpp_unicode_characters\fP   200704"
.br
.ti -1c
.RI "#define \fB_STDC_PREDEF_H\fP   1"
.br
.ti -1c
.RI "#define \fB__cpp_decltype_auto\fP   201304"
.br
.ti -1c
.RI "#define \fB__GCC_ATOMIC_INT_LOCK_FREE\fP   2"
.br
.ti -1c
.RI "#define \fB__FLT128_MAX_EXP__\fP   16384"
.br
.ti -1c
.RI "#define \fB__FLT32_MANT_DIG__\fP   24"
.br
.ti -1c
.RI "#define \fB__FLOAT_WORD_ORDER__\fP   \fB__ORDER_LITTLE_ENDIAN__\fP"
.br
.ti -1c
.RI "#define \fB__STDC_IEC_559_COMPLEX__\fP   1"
.br
.ti -1c
.RI "#define \fB__FLT128_HAS_DENORM__\fP   1"
.br
.ti -1c
.RI "#define \fB__FLT128_DIG__\fP   33"
.br
.ti -1c
.RI "#define \fB__SCHAR_WIDTH__\fP   8"
.br
.ti -1c
.RI "#define \fB__INT32_C\fP(c)   c"
.br
.ti -1c
.RI "#define \fB__DEC64_EPSILON__\fP   1E\-15DD"
.br
.ti -1c
.RI "#define \fB__ORDER_PDP_ENDIAN__\fP   3412"
.br
.ti -1c
.RI "#define \fB__DEC128_MIN_EXP__\fP   (\-6142)"
.br
.ti -1c
.RI "#define \fB__FLT32_MAX_10_EXP__\fP   38"
.br
.ti -1c
.RI "#define \fB__INT_FAST32_TYPE__\fP   long int"
.br
.ti -1c
.RI "#define \fB__UINT_LEAST16_TYPE__\fP   short unsigned int"
.br
.ti -1c
.RI "#define \fB__FLT64X_HAS_INFINITY__\fP   1"
.br
.ti -1c
.RI "#define \fBunix\fP   1"
.br
.ti -1c
.RI "#define \fB__INT16_MAX__\fP   0x7fff"
.br
.ti -1c
.RI "#define \fB__cpp_rtti\fP   199711"
.br
.ti -1c
.RI "#define \fB__SIZE_TYPE__\fP   long unsigned int"
.br
.ti -1c
.RI "#define \fB__UINT64_MAX__\fP   0xffffffffffffffffUL"
.br
.ti -1c
.RI "#define \fB__FLT64X_DIG__\fP   18"
.br
.ti -1c
.RI "#define \fB__INT8_TYPE__\fP   signed char"
.br
.ti -1c
.RI "#define \fB__cpp_digit_separators\fP   201309"
.br
.ti -1c
.RI "#define \fB__ELF__\fP   1"
.br
.ti -1c
.RI "#define \fB__GCC_ASM_FLAG_OUTPUTS__\fP   1"
.br
.ti -1c
.RI "#define \fB__FLT_RADIX__\fP   2"
.br
.ti -1c
.RI "#define \fB__INT_LEAST16_TYPE__\fP   short int"
.br
.ti -1c
.RI "#define \fB__LDBL_EPSILON__\fP   1\&.08420217248550443400745280086994171e\-19L"
.br
.ti -1c
.RI "#define \fB__UINTMAX_C\fP(c)   c ## UL"
.br
.ti -1c
.RI "#define \fB__GLIBCXX_BITSIZE_INT_N_0\fP   128"
.br
.ti -1c
.RI "#define \fB__k8\fP   1"
.br
.ti -1c
.RI "#define \fB__SIG_ATOMIC_MAX__\fP   0x7fffffff"
.br
.ti -1c
.RI "#define \fB__GCC_ATOMIC_WCHAR_T_LOCK_FREE\fP   2"
.br
.ti -1c
.RI "#define \fB__cpp_sized_deallocation\fP   201309"
.br
.ti -1c
.RI "#define \fB__SIZEOF_PTRDIFF_T__\fP   8"
.br
.ti -1c
.RI "#define \fB__FLT32X_MANT_DIG__\fP   53"
.br
.ti -1c
.RI "#define \fB__x86_64__\fP   1"
.br
.ti -1c
.RI "#define \fB__FLT32X_MIN_EXP__\fP   (\-1021)"
.br
.ti -1c
.RI "#define \fB__DEC32_SUBNORMAL_MIN__\fP   0\&.000001E\-95DF"
.br
.ti -1c
.RI "#define \fB__INT_FAST16_MAX__\fP   0x7fffffffffffffffL"
.br
.ti -1c
.RI "#define \fB__FLT64_DIG__\fP   15"
.br
.ti -1c
.RI "#define \fB__UINT_FAST32_MAX__\fP   0xffffffffffffffffUL"
.br
.ti -1c
.RI "#define \fB__UINT_LEAST64_TYPE__\fP   long unsigned int"
.br
.ti -1c
.RI "#define \fB__FLT_HAS_QUIET_NAN__\fP   1"
.br
.ti -1c
.RI "#define \fB__FLT_MAX_10_EXP__\fP   38"
.br
.ti -1c
.RI "#define \fB__LONG_MAX__\fP   0x7fffffffffffffffL"
.br
.ti -1c
.RI "#define \fB__FLT64X_HAS_DENORM__\fP   1"
.br
.ti -1c
.RI "#define \fB__DEC128_SUBNORMAL_MIN__\fP   0\&.000000000000000000000000000000001E\-6143DL"
.br
.ti -1c
.RI "#define \fB__FLT_HAS_INFINITY__\fP   1"
.br
.ti -1c
.RI "#define \fB__cpp_unicode_literals\fP   200710"
.br
.ti -1c
.RI "#define \fB__UINT_FAST16_TYPE__\fP   long unsigned int"
.br
.ti -1c
.RI "#define \fB__DEC64_MAX__\fP   9\&.999999999999999E384DD"
.br
.ti -1c
.RI "#define \fB__INT_FAST32_WIDTH__\fP   64"
.br
.ti -1c
.RI "#define \fB__CHAR16_TYPE__\fP   short unsigned int"
.br
.ti -1c
.RI "#define \fB__PRAGMA_REDEFINE_EXTNAME\fP   1"
.br
.ti -1c
.RI "#define \fB__SIZE_WIDTH__\fP   64"
.br
.ti -1c
.RI "#define \fB__SEG_FS\fP   1"
.br
.ti -1c
.RI "#define \fB__INT_LEAST16_MAX__\fP   0x7fff"
.br
.ti -1c
.RI "#define \fB__DEC64_MANT_DIG__\fP   16"
.br
.ti -1c
.RI "#define \fB__UINT_LEAST32_MAX__\fP   0xffffffffU"
.br
.ti -1c
.RI "#define \fB__SEG_GS\fP   1"
.br
.ti -1c
.RI "#define \fB__FLT32_DENORM_MIN__\fP   1\&.40129846432481707092372958328991613e\-45F32"
.br
.ti -1c
.RI "#define \fB__GCC_ATOMIC_LONG_LOCK_FREE\fP   2"
.br
.ti -1c
.RI "#define \fB__SIG_ATOMIC_WIDTH__\fP   32"
.br
.ti -1c
.RI "#define \fB__INT_LEAST64_TYPE__\fP   long int"
.br
.ti -1c
.RI "#define \fB__INT16_TYPE__\fP   short int"
.br
.ti -1c
.RI "#define \fB__INT_LEAST8_TYPE__\fP   signed char"
.br
.ti -1c
.RI "#define \fB__DEC32_MAX_EXP__\fP   97"
.br
.ti -1c
.RI "#define \fB__INT_FAST8_MAX__\fP   0x7f"
.br
.ti -1c
.RI "#define \fB__FLT128_MAX__\fP   1\&.18973149535723176508575932662800702e+4932F128"
.br
.ti -1c
.RI "#define \fB__INTPTR_MAX__\fP   0x7fffffffffffffffL"
.br
.ti -1c
.RI "#define \fBlinux\fP   1"
.br
.ti -1c
.RI "#define \fB__cpp_range_based_for\fP   200907"
.br
.ti -1c
.RI "#define \fB__FLT64_HAS_QUIET_NAN__\fP   1"
.br
.ti -1c
.RI "#define \fB__FLT32_MIN_10_EXP__\fP   (\-37)"
.br
.ti -1c
.RI "#define \fB__SSE2__\fP   1"
.br
.ti -1c
.RI "#define \fB__EXCEPTIONS\fP   1"
.br
.ti -1c
.RI "#define \fB__LDBL_MANT_DIG__\fP   64"
.br
.ti -1c
.RI "#define \fB__DBL_HAS_QUIET_NAN__\fP   1"
.br
.ti -1c
.RI "#define \fB__FLT64_HAS_INFINITY__\fP   1"
.br
.ti -1c
.RI "#define \fB__FLT64X_MAX__\fP   1\&.18973149535723176502126385303097021e+4932F64x"
.br
.ti -1c
.RI "#define \fB__SIG_ATOMIC_MIN__\fP   (\-\fB__SIG_ATOMIC_MAX__\fP \- 1)"
.br
.ti -1c
.RI "#define \fB__code_model_small__\fP   1"
.br
.ti -1c
.RI "#define \fB__cpp_return_type_deduction\fP   201304"
.br
.ti -1c
.RI "#define \fB__k8__\fP   1"
.br
.ti -1c
.RI "#define \fB__INTPTR_TYPE__\fP   long int"
.br
.ti -1c
.RI "#define \fB__UINT16_TYPE__\fP   short unsigned int"
.br
.ti -1c
.RI "#define \fB__WCHAR_TYPE__\fP   int"
.br
.ti -1c
.RI "#define \fB__SIZEOF_FLOAT__\fP   4"
.br
.ti -1c
.RI "#define \fB__pic__\fP   2"
.br
.ti -1c
.RI "#define \fB__UINTPTR_MAX__\fP   0xffffffffffffffffUL"
.br
.ti -1c
.RI "#define \fB__INT_FAST64_WIDTH__\fP   64"
.br
.ti -1c
.RI "#define \fB__DEC64_MIN_EXP__\fP   (\-382)"
.br
.ti -1c
.RI "#define \fB__cpp_decltype\fP   200707"
.br
.ti -1c
.RI "#define \fB__FLT32_DECIMAL_DIG__\fP   9"
.br
.ti -1c
.RI "#define \fB__INT_FAST64_MAX__\fP   0x7fffffffffffffffL"
.br
.ti -1c
.RI "#define \fB__GCC_ATOMIC_TEST_AND_SET_TRUEVAL\fP   1"
.br
.ti -1c
.RI "#define \fB__FLT_DIG__\fP   6"
.br
.ti -1c
.RI "#define \fB__FLT64X_MAX_EXP__\fP   16384"
.br
.ti -1c
.RI "#define \fB__UINT_FAST64_TYPE__\fP   long unsigned int"
.br
.ti -1c
.RI "#define \fB__INT_MAX__\fP   0x7fffffff"
.br
.ti -1c
.RI "#define \fB__amd64__\fP   1"
.br
.ti -1c
.RI "#define \fB__INT64_TYPE__\fP   long int"
.br
.ti -1c
.RI "#define \fB__FLT_MAX_EXP__\fP   128"
.br
.ti -1c
.RI "#define \fB__ORDER_BIG_ENDIAN__\fP   4321"
.br
.ti -1c
.RI "#define \fB__DBL_MANT_DIG__\fP   53"
.br
.ti -1c
.RI "#define \fB__cpp_inheriting_constructors\fP   201511"
.br
.ti -1c
.RI "#define \fBQT_CORE_LIB\fP   1"
.br
.ti -1c
.RI "#define \fB__SIZEOF_FLOAT128__\fP   16"
.br
.ti -1c
.RI "#define \fB__INT_LEAST64_MAX__\fP   0x7fffffffffffffffL"
.br
.ti -1c
.RI "#define \fB__DEC64_MIN__\fP   1E\-383DD"
.br
.ti -1c
.RI "#define \fB__WINT_TYPE__\fP   unsigned int"
.br
.ti -1c
.RI "#define \fB__UINT_LEAST32_TYPE__\fP   unsigned int"
.br
.ti -1c
.RI "#define \fB__SIZEOF_SHORT__\fP   2"
.br
.ti -1c
.RI "#define \fB__SSE__\fP   1"
.br
.ti -1c
.RI "#define \fB__LDBL_MIN_EXP__\fP   (\-16381)"
.br
.ti -1c
.RI "#define \fB__FLT64_MAX__\fP   1\&.79769313486231570814527423731704357e+308F64"
.br
.ti -1c
.RI "#define \fB__WINT_WIDTH__\fP   32"
.br
.ti -1c
.RI "#define \fB__INT_LEAST8_MAX__\fP   0x7f"
.br
.ti -1c
.RI "#define \fB__FLT32X_MAX_10_EXP__\fP   308"
.br
.ti -1c
.RI "#define \fB__SIZEOF_INT128__\fP   16"
.br
.ti -1c
.RI "#define \fB__LDBL_MAX_10_EXP__\fP   4932"
.br
.ti -1c
.RI "#define \fB__ATOMIC_RELAXED\fP   0"
.br
.ti -1c
.RI "#define \fB__DBL_EPSILON__\fP   double(2\&.22044604925031308084726333618164062e\-16L)"
.br
.ti -1c
.RI "#define \fB__FLT128_MIN__\fP   3\&.36210314311209350626267781732175260e\-4932F128"
.br
.ti -1c
.RI "#define \fB_LP64\fP   1"
.br
.ti -1c
.RI "#define \fB__UINT8_C\fP(c)   c"
.br
.ti -1c
.RI "#define \fB__FLT64_MAX_EXP__\fP   1024"
.br
.ti -1c
.RI "#define \fB__INT_LEAST32_TYPE__\fP   int"
.br
.ti -1c
.RI "#define \fB__SIZEOF_WCHAR_T__\fP   4"
.br
.ti -1c
.RI "#define \fB__FLT128_HAS_QUIET_NAN__\fP   1"
.br
.ti -1c
.RI "#define \fB__INT_FAST8_TYPE__\fP   signed char"
.br
.ti -1c
.RI "#define \fB__FLT64X_MIN__\fP   3\&.36210314311209350626267781732175260e\-4932F64x"
.br
.ti -1c
.RI "#define \fB__GNUC_STDC_INLINE__\fP   1"
.br
.ti -1c
.RI "#define \fB__FLT64_HAS_DENORM__\fP   1"
.br
.ti -1c
.RI "#define \fB__FLT32_EPSILON__\fP   1\&.19209289550781250000000000000000000e\-7F32"
.br
.ti -1c
.RI "#define \fB__DBL_DECIMAL_DIG__\fP   17"
.br
.ti -1c
.RI "#define \fB__STDC_UTF_32__\fP   1"
.br
.ti -1c
.RI "#define \fB__INT_FAST8_WIDTH__\fP   8"
.br
.ti -1c
.RI "#define \fB__FXSR__\fP   1"
.br
.ti -1c
.RI "#define \fB__DEC_EVAL_METHOD__\fP   2"
.br
.ti -1c
.RI "#define \fB__FLT32X_MAX__\fP   1\&.79769313486231570814527423731704357e+308F32x"
.br
.ti -1c
.RI "#define \fB__cpp_runtime_arrays\fP   198712"
.br
.ti -1c
.RI "#define \fB__UINT64_TYPE__\fP   long unsigned int"
.br
.ti -1c
.RI "#define \fB__UINT32_C\fP(c)   c ## U"
.br
.ti -1c
.RI "#define \fB__INTMAX_MAX__\fP   0x7fffffffffffffffL"
.br
.ti -1c
.RI "#define \fB__cpp_alias_templates\fP   200704"
.br
.ti -1c
.RI "#define \fB__BYTE_ORDER__\fP   \fB__ORDER_LITTLE_ENDIAN__\fP"
.br
.ti -1c
.RI "#define \fB__FLT_DENORM_MIN__\fP   1\&.40129846432481707092372958328991613e\-45F"
.br
.ti -1c
.RI "#define \fB__INT8_MAX__\fP   0x7f"
.br
.ti -1c
.RI "#define \fB__LONG_WIDTH__\fP   64"
.br
.ti -1c
.RI "#define \fB__PIC__\fP   2"
.br
.ti -1c
.RI "#define \fB__UINT_FAST32_TYPE__\fP   long unsigned int"
.br
.ti -1c
.RI "#define \fB__CHAR32_TYPE__\fP   unsigned int"
.br
.ti -1c
.RI "#define \fB__FLT_MAX__\fP   3\&.40282346638528859811704183484516925e+38F"
.br
.ti -1c
.RI "#define \fB__cpp_constexpr\fP   201304"
.br
.ti -1c
.RI "#define \fB__INT32_TYPE__\fP   int"
.br
.ti -1c
.RI "#define \fB__SIZEOF_DOUBLE__\fP   8"
.br
.ti -1c
.RI "#define \fB__cpp_exceptions\fP   199711"
.br
.ti -1c
.RI "#define \fB__FLT_MIN_10_EXP__\fP   (\-37)"
.br
.ti -1c
.RI "#define \fB__FLT64_MIN__\fP   2\&.22507385850720138309023271733240406e\-308F64"
.br
.ti -1c
.RI "#define \fB__INT_LEAST32_WIDTH__\fP   32"
.br
.ti -1c
.RI "#define \fB__INTMAX_TYPE__\fP   long int"
.br
.ti -1c
.RI "#define \fB__DEC128_MAX_EXP__\fP   6145"
.br
.ti -1c
.RI "#define \fB__FLT32X_HAS_QUIET_NAN__\fP   1"
.br
.ti -1c
.RI "#define \fB__ATOMIC_CONSUME\fP   1"
.br
.ti -1c
.RI "#define \fB__GNUC_MINOR__\fP   3"
.br
.ti -1c
.RI "#define \fB__GLIBCXX_TYPE_INT_N_0\fP   __int128"
.br
.ti -1c
.RI "#define \fB__INT_FAST16_WIDTH__\fP   64"
.br
.ti -1c
.RI "#define \fB__UINTMAX_MAX__\fP   0xffffffffffffffffUL"
.br
.ti -1c
.RI "#define \fB__DEC32_MANT_DIG__\fP   7"
.br
.ti -1c
.RI "#define \fB__FLT32X_DENORM_MIN__\fP   4\&.94065645841246544176568792868221372e\-324F32x"
.br
.ti -1c
.RI "#define \fB__DBL_MAX_10_EXP__\fP   308"
.br
.ti -1c
.RI "#define \fB__LDBL_DENORM_MIN__\fP   3\&.64519953188247460252840593361941982e\-4951L"
.br
.ti -1c
.RI "#define \fB__INT16_C\fP(c)   c"
.br
.ti -1c
.RI "#define \fB__cpp_generic_lambdas\fP   201304"
.br
.ti -1c
.RI "#define \fB__STDC__\fP   1"
.br
.ti -1c
.RI "#define \fB__FLT32X_DIG__\fP   15"
.br
.ti -1c
.RI "#define \fB__PTRDIFF_TYPE__\fP   long int"
.br
.ti -1c
.RI "#define \fB__ATOMIC_SEQ_CST\fP   5"
.br
.ti -1c
.RI "#define \fB__UINT32_TYPE__\fP   unsigned int"
.br
.ti -1c
.RI "#define \fB__FLT32X_MIN_10_EXP__\fP   (\-307)"
.br
.ti -1c
.RI "#define \fB__UINTPTR_TYPE__\fP   long unsigned int"
.br
.ti -1c
.RI "#define \fB__DEC64_SUBNORMAL_MIN__\fP   0\&.000000000000001E\-383DD"
.br
.ti -1c
.RI "#define \fB__DEC128_MANT_DIG__\fP   34"
.br
.ti -1c
.RI "#define \fB__LDBL_MIN_10_EXP__\fP   (\-4931)"
.br
.ti -1c
.RI "#define \fB__FLT128_EPSILON__\fP   1\&.92592994438723585305597794258492732e\-34F128"
.br
.ti -1c
.RI "#define \fB__SSE_MATH__\fP   1"
.br
.ti -1c
.RI "#define \fB__SIZEOF_LONG_LONG__\fP   8"
.br
.ti -1c
.RI "#define \fB__cpp_user_defined_literals\fP   200809"
.br
.ti -1c
.RI "#define \fB__FLT128_DECIMAL_DIG__\fP   36"
.br
.ti -1c
.RI "#define \fB__GCC_ATOMIC_LLONG_LOCK_FREE\fP   2"
.br
.ti -1c
.RI "#define \fB__FLT32X_MIN__\fP   2\&.22507385850720138309023271733240406e\-308F32x"
.br
.ti -1c
.RI "#define \fB__LDBL_DIG__\fP   18"
.br
.ti -1c
.RI "#define \fB__FLT_DECIMAL_DIG__\fP   9"
.br
.ti -1c
.RI "#define \fB__UINT_FAST16_MAX__\fP   0xffffffffffffffffUL"
.br
.ti -1c
.RI "#define \fB__GCC_ATOMIC_SHORT_LOCK_FREE\fP   2"
.br
.ti -1c
.RI "#define \fB__INT_LEAST64_WIDTH__\fP   64"
.br
.ti -1c
.RI "#define \fB__UINT_FAST8_TYPE__\fP   unsigned char"
.br
.ti -1c
.RI "#define \fB_GNU_SOURCE\fP   1"
.br
.ti -1c
.RI "#define \fB__cpp_init_captures\fP   201304"
.br
.ti -1c
.RI "#define \fB__ATOMIC_ACQ_REL\fP   4"
.br
.ti -1c
.RI "#define \fB__ATOMIC_RELEASE\fP   3"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define __amd64   1"

.SS "#define __amd64__   1"

.SS "#define __ATOMIC_ACQ_REL   4"

.SS "#define __ATOMIC_ACQUIRE   2"

.SS "#define __ATOMIC_CONSUME   1"

.SS "#define __ATOMIC_HLE_ACQUIRE   65536"

.SS "#define __ATOMIC_HLE_RELEASE   131072"

.SS "#define __ATOMIC_RELAXED   0"

.SS "#define __ATOMIC_RELEASE   3"

.SS "#define __ATOMIC_SEQ_CST   5"

.SS "#define __BIGGEST_ALIGNMENT__   16"

.SS "#define __BYTE_ORDER__   \fB__ORDER_LITTLE_ENDIAN__\fP"

.SS "#define __CHAR16_TYPE__   short unsigned int"

.SS "#define __CHAR32_TYPE__   unsigned int"

.SS "#define __CHAR_BIT__   8"

.SS "#define __code_model_small__   1"

.SS "#define __cplusplus   201402L"

.SS "#define __cpp_aggregate_nsdmi   201304"

.SS "#define __cpp_alias_templates   200704"

.SS "#define __cpp_attributes   200809"

.SS "#define __cpp_binary_literals   201304"

.SS "#define __cpp_constexpr   201304"

.SS "#define __cpp_decltype   200707"

.SS "#define __cpp_decltype_auto   201304"

.SS "#define __cpp_delegating_constructors   200604"

.SS "#define __cpp_digit_separators   201309"

.SS "#define __cpp_exceptions   199711"

.SS "#define __cpp_generic_lambdas   201304"

.SS "#define __cpp_hex_float   201603"

.SS "#define __cpp_inheriting_constructors   201511"

.SS "#define __cpp_init_captures   201304"

.SS "#define __cpp_initializer_lists   200806"

.SS "#define __cpp_lambdas   200907"

.SS "#define __cpp_nsdmi   200809"

.SS "#define __cpp_range_based_for   200907"

.SS "#define __cpp_raw_strings   200710"

.SS "#define __cpp_ref_qualifiers   200710"

.SS "#define __cpp_return_type_deduction   201304"

.SS "#define __cpp_rtti   199711"

.SS "#define __cpp_runtime_arrays   198712"

.SS "#define __cpp_rvalue_reference   200610"

.SS "#define __cpp_rvalue_references   200610"

.SS "#define __cpp_sized_deallocation   201309"

.SS "#define __cpp_static_assert   200410"

.SS "#define __cpp_threadsafe_static_init   200806"

.SS "#define __cpp_unicode_characters   200704"

.SS "#define __cpp_unicode_literals   200710"

.SS "#define __cpp_user_defined_literals   200809"

.SS "#define __cpp_variable_templates   201304"

.SS "#define __cpp_variadic_templates   200704"

.SS "#define __DBL_DECIMAL_DIG__   17"

.SS "#define __DBL_DENORM_MIN__   double(4\&.94065645841246544176568792868221372e\-324L)"

.SS "#define __DBL_DIG__   15"

.SS "#define __DBL_EPSILON__   double(2\&.22044604925031308084726333618164062e\-16L)"

.SS "#define __DBL_HAS_DENORM__   1"

.SS "#define __DBL_HAS_INFINITY__   1"

.SS "#define __DBL_HAS_QUIET_NAN__   1"

.SS "#define __DBL_MANT_DIG__   53"

.SS "#define __DBL_MAX_10_EXP__   308"

.SS "#define __DBL_MAX__   double(1\&.79769313486231570814527423731704357e+308L)"

.SS "#define __DBL_MAX_EXP__   1024"

.SS "#define __DBL_MIN_10_EXP__   (\-307)"

.SS "#define __DBL_MIN__   double(2\&.22507385850720138309023271733240406e\-308L)"

.SS "#define __DBL_MIN_EXP__   (\-1021)"

.SS "#define __DEC128_EPSILON__   1E\-33DL"

.SS "#define __DEC128_MANT_DIG__   34"

.SS "#define __DEC128_MAX__   9\&.999999999999999999999999999999999E6144DL"

.SS "#define __DEC128_MAX_EXP__   6145"

.SS "#define __DEC128_MIN__   1E\-6143DL"

.SS "#define __DEC128_MIN_EXP__   (\-6142)"

.SS "#define __DEC128_SUBNORMAL_MIN__   0\&.000000000000000000000000000000001E\-6143DL"

.SS "#define __DEC32_EPSILON__   1E\-6DF"

.SS "#define __DEC32_MANT_DIG__   7"

.SS "#define __DEC32_MAX__   9\&.999999E96DF"

.SS "#define __DEC32_MAX_EXP__   97"

.SS "#define __DEC32_MIN__   1E\-95DF"

.SS "#define __DEC32_MIN_EXP__   (\-94)"

.SS "#define __DEC32_SUBNORMAL_MIN__   0\&.000001E\-95DF"

.SS "#define __DEC64_EPSILON__   1E\-15DD"

.SS "#define __DEC64_MANT_DIG__   16"

.SS "#define __DEC64_MAX__   9\&.999999999999999E384DD"

.SS "#define __DEC64_MAX_EXP__   385"

.SS "#define __DEC64_MIN__   1E\-383DD"

.SS "#define __DEC64_MIN_EXP__   (\-382)"

.SS "#define __DEC64_SUBNORMAL_MIN__   0\&.000000000000001E\-383DD"

.SS "#define __DEC_EVAL_METHOD__   2"

.SS "#define __DECIMAL_BID_FORMAT__   1"

.SS "#define __DECIMAL_DIG__   21"

.SS "#define __DEPRECATED   1"

.SS "#define __ELF__   1"

.SS "#define __EXCEPTIONS   1"

.SS "#define __FINITE_MATH_ONLY__   0"

.SS "#define __FLOAT_WORD_ORDER__   \fB__ORDER_LITTLE_ENDIAN__\fP"

.SS "#define __FLT128_DECIMAL_DIG__   36"

.SS "#define __FLT128_DENORM_MIN__   6\&.47517511943802511092443895822764655e\-4966F128"

.SS "#define __FLT128_DIG__   33"

.SS "#define __FLT128_EPSILON__   1\&.92592994438723585305597794258492732e\-34F128"

.SS "#define __FLT128_HAS_DENORM__   1"

.SS "#define __FLT128_HAS_INFINITY__   1"

.SS "#define __FLT128_HAS_QUIET_NAN__   1"

.SS "#define __FLT128_MANT_DIG__   113"

.SS "#define __FLT128_MAX_10_EXP__   4932"

.SS "#define __FLT128_MAX__   1\&.18973149535723176508575932662800702e+4932F128"

.SS "#define __FLT128_MAX_EXP__   16384"

.SS "#define __FLT128_MIN_10_EXP__   (\-4931)"

.SS "#define __FLT128_MIN__   3\&.36210314311209350626267781732175260e\-4932F128"

.SS "#define __FLT128_MIN_EXP__   (\-16381)"

.SS "#define __FLT32_DECIMAL_DIG__   9"

.SS "#define __FLT32_DENORM_MIN__   1\&.40129846432481707092372958328991613e\-45F32"

.SS "#define __FLT32_DIG__   6"

.SS "#define __FLT32_EPSILON__   1\&.19209289550781250000000000000000000e\-7F32"

.SS "#define __FLT32_HAS_DENORM__   1"

.SS "#define __FLT32_HAS_INFINITY__   1"

.SS "#define __FLT32_HAS_QUIET_NAN__   1"

.SS "#define __FLT32_MANT_DIG__   24"

.SS "#define __FLT32_MAX_10_EXP__   38"

.SS "#define __FLT32_MAX__   3\&.40282346638528859811704183484516925e+38F32"

.SS "#define __FLT32_MAX_EXP__   128"

.SS "#define __FLT32_MIN_10_EXP__   (\-37)"

.SS "#define __FLT32_MIN__   1\&.17549435082228750796873653722224568e\-38F32"

.SS "#define __FLT32_MIN_EXP__   (\-125)"

.SS "#define __FLT32X_DECIMAL_DIG__   17"

.SS "#define __FLT32X_DENORM_MIN__   4\&.94065645841246544176568792868221372e\-324F32x"

.SS "#define __FLT32X_DIG__   15"

.SS "#define __FLT32X_EPSILON__   2\&.22044604925031308084726333618164062e\-16F32x"

.SS "#define __FLT32X_HAS_DENORM__   1"

.SS "#define __FLT32X_HAS_INFINITY__   1"

.SS "#define __FLT32X_HAS_QUIET_NAN__   1"

.SS "#define __FLT32X_MANT_DIG__   53"

.SS "#define __FLT32X_MAX_10_EXP__   308"

.SS "#define __FLT32X_MAX__   1\&.79769313486231570814527423731704357e+308F32x"

.SS "#define __FLT32X_MAX_EXP__   1024"

.SS "#define __FLT32X_MIN_10_EXP__   (\-307)"

.SS "#define __FLT32X_MIN__   2\&.22507385850720138309023271733240406e\-308F32x"

.SS "#define __FLT32X_MIN_EXP__   (\-1021)"

.SS "#define __FLT64_DECIMAL_DIG__   17"

.SS "#define __FLT64_DENORM_MIN__   4\&.94065645841246544176568792868221372e\-324F64"

.SS "#define __FLT64_DIG__   15"

.SS "#define __FLT64_EPSILON__   2\&.22044604925031308084726333618164062e\-16F64"

.SS "#define __FLT64_HAS_DENORM__   1"

.SS "#define __FLT64_HAS_INFINITY__   1"

.SS "#define __FLT64_HAS_QUIET_NAN__   1"

.SS "#define __FLT64_MANT_DIG__   53"

.SS "#define __FLT64_MAX_10_EXP__   308"

.SS "#define __FLT64_MAX__   1\&.79769313486231570814527423731704357e+308F64"

.SS "#define __FLT64_MAX_EXP__   1024"

.SS "#define __FLT64_MIN_10_EXP__   (\-307)"

.SS "#define __FLT64_MIN__   2\&.22507385850720138309023271733240406e\-308F64"

.SS "#define __FLT64_MIN_EXP__   (\-1021)"

.SS "#define __FLT64X_DECIMAL_DIG__   21"

.SS "#define __FLT64X_DENORM_MIN__   3\&.64519953188247460252840593361941982e\-4951F64x"

.SS "#define __FLT64X_DIG__   18"

.SS "#define __FLT64X_EPSILON__   1\&.08420217248550443400745280086994171e\-19F64x"

.SS "#define __FLT64X_HAS_DENORM__   1"

.SS "#define __FLT64X_HAS_INFINITY__   1"

.SS "#define __FLT64X_HAS_QUIET_NAN__   1"

.SS "#define __FLT64X_MANT_DIG__   64"

.SS "#define __FLT64X_MAX_10_EXP__   4932"

.SS "#define __FLT64X_MAX__   1\&.18973149535723176502126385303097021e+4932F64x"

.SS "#define __FLT64X_MAX_EXP__   16384"

.SS "#define __FLT64X_MIN_10_EXP__   (\-4931)"

.SS "#define __FLT64X_MIN__   3\&.36210314311209350626267781732175260e\-4932F64x"

.SS "#define __FLT64X_MIN_EXP__   (\-16381)"

.SS "#define __FLT_DECIMAL_DIG__   9"

.SS "#define __FLT_DENORM_MIN__   1\&.40129846432481707092372958328991613e\-45F"

.SS "#define __FLT_DIG__   6"

.SS "#define __FLT_EPSILON__   1\&.19209289550781250000000000000000000e\-7F"

.SS "#define __FLT_EVAL_METHOD__   0"

.SS "#define __FLT_EVAL_METHOD_TS_18661_3__   0"

.SS "#define __FLT_HAS_DENORM__   1"

.SS "#define __FLT_HAS_INFINITY__   1"

.SS "#define __FLT_HAS_QUIET_NAN__   1"

.SS "#define __FLT_MANT_DIG__   24"

.SS "#define __FLT_MAX_10_EXP__   38"

.SS "#define __FLT_MAX__   3\&.40282346638528859811704183484516925e+38F"

.SS "#define __FLT_MAX_EXP__   128"

.SS "#define __FLT_MIN_10_EXP__   (\-37)"

.SS "#define __FLT_MIN__   1\&.17549435082228750796873653722224568e\-38F"

.SS "#define __FLT_MIN_EXP__   (\-125)"

.SS "#define __FLT_RADIX__   2"

.SS "#define __FXSR__   1"

.SS "#define __GCC_ASM_FLAG_OUTPUTS__   1"

.SS "#define __GCC_ATOMIC_BOOL_LOCK_FREE   2"

.SS "#define __GCC_ATOMIC_CHAR16_T_LOCK_FREE   2"

.SS "#define __GCC_ATOMIC_CHAR32_T_LOCK_FREE   2"

.SS "#define __GCC_ATOMIC_CHAR_LOCK_FREE   2"

.SS "#define __GCC_ATOMIC_INT_LOCK_FREE   2"

.SS "#define __GCC_ATOMIC_LLONG_LOCK_FREE   2"

.SS "#define __GCC_ATOMIC_LONG_LOCK_FREE   2"

.SS "#define __GCC_ATOMIC_POINTER_LOCK_FREE   2"

.SS "#define __GCC_ATOMIC_SHORT_LOCK_FREE   2"

.SS "#define __GCC_ATOMIC_TEST_AND_SET_TRUEVAL   1"

.SS "#define __GCC_ATOMIC_WCHAR_T_LOCK_FREE   2"

.SS "#define __GCC_HAVE_DWARF2_CFI_ASM   1"

.SS "#define __GCC_HAVE_SYNC_COMPARE_AND_SWAP_1   1"

.SS "#define __GCC_HAVE_SYNC_COMPARE_AND_SWAP_2   1"

.SS "#define __GCC_HAVE_SYNC_COMPARE_AND_SWAP_4   1"

.SS "#define __GCC_HAVE_SYNC_COMPARE_AND_SWAP_8   1"

.SS "#define __GCC_IEC_559   2"

.SS "#define __GCC_IEC_559_COMPLEX   2"

.SS "#define __GLIBCXX_BITSIZE_INT_N_0   128"

.SS "#define __GLIBCXX_TYPE_INT_N_0   __int128"

.SS "#define __gnu_linux__   1"

.SS "#define __GNUC__   7"

.SS "#define __GNUC_MINOR__   3"

.SS "#define __GNUC_PATCHLEVEL__   0"

.SS "#define __GNUC_STDC_INLINE__   1"

.SS "#define __GNUG__   7"

.SS "#define __GXX_ABI_VERSION   1011"

.SS "#define __GXX_EXPERIMENTAL_CXX0X__   1"

.SS "#define __GXX_RTTI   1"

.SS "#define __GXX_WEAK__   1"

.SS "#define __has_include(STR)   __has_include__(STR)"

.SS "#define __has_include_next(STR)   __has_include_next__(STR)"

.SS "#define __INT16_C(c)   c"

.SS "#define __INT16_MAX__   0x7fff"

.SS "#define __INT16_TYPE__   short int"

.SS "#define __INT32_C(c)   c"

.SS "#define __INT32_MAX__   0x7fffffff"

.SS "#define __INT32_TYPE__   int"

.SS "#define __INT64_C(c)   c ## L"

.SS "#define __INT64_MAX__   0x7fffffffffffffffL"

.SS "#define __INT64_TYPE__   long int"

.SS "#define __INT8_C(c)   c"

.SS "#define __INT8_MAX__   0x7f"

.SS "#define __INT8_TYPE__   signed char"

.SS "#define __INT_FAST16_MAX__   0x7fffffffffffffffL"

.SS "#define __INT_FAST16_TYPE__   long int"

.SS "#define __INT_FAST16_WIDTH__   64"

.SS "#define __INT_FAST32_MAX__   0x7fffffffffffffffL"

.SS "#define __INT_FAST32_TYPE__   long int"

.SS "#define __INT_FAST32_WIDTH__   64"

.SS "#define __INT_FAST64_MAX__   0x7fffffffffffffffL"

.SS "#define __INT_FAST64_TYPE__   long int"

.SS "#define __INT_FAST64_WIDTH__   64"

.SS "#define __INT_FAST8_MAX__   0x7f"

.SS "#define __INT_FAST8_TYPE__   signed char"

.SS "#define __INT_FAST8_WIDTH__   8"

.SS "#define __INT_LEAST16_MAX__   0x7fff"

.SS "#define __INT_LEAST16_TYPE__   short int"

.SS "#define __INT_LEAST16_WIDTH__   16"

.SS "#define __INT_LEAST32_MAX__   0x7fffffff"

.SS "#define __INT_LEAST32_TYPE__   int"

.SS "#define __INT_LEAST32_WIDTH__   32"

.SS "#define __INT_LEAST64_MAX__   0x7fffffffffffffffL"

.SS "#define __INT_LEAST64_TYPE__   long int"

.SS "#define __INT_LEAST64_WIDTH__   64"

.SS "#define __INT_LEAST8_MAX__   0x7f"

.SS "#define __INT_LEAST8_TYPE__   signed char"

.SS "#define __INT_LEAST8_WIDTH__   8"

.SS "#define __INT_MAX__   0x7fffffff"

.SS "#define __INT_WIDTH__   32"

.SS "#define __INTMAX_C(c)   c ## L"

.SS "#define __INTMAX_MAX__   0x7fffffffffffffffL"

.SS "#define __INTMAX_TYPE__   long int"

.SS "#define __INTMAX_WIDTH__   64"

.SS "#define __INTPTR_MAX__   0x7fffffffffffffffL"

.SS "#define __INTPTR_TYPE__   long int"

.SS "#define __INTPTR_WIDTH__   64"

.SS "#define __k8   1"

.SS "#define __k8__   1"

.SS "#define __LDBL_DECIMAL_DIG__   21"

.SS "#define __LDBL_DENORM_MIN__   3\&.64519953188247460252840593361941982e\-4951L"

.SS "#define __LDBL_DIG__   18"

.SS "#define __LDBL_EPSILON__   1\&.08420217248550443400745280086994171e\-19L"

.SS "#define __LDBL_HAS_DENORM__   1"

.SS "#define __LDBL_HAS_INFINITY__   1"

.SS "#define __LDBL_HAS_QUIET_NAN__   1"

.SS "#define __LDBL_MANT_DIG__   64"

.SS "#define __LDBL_MAX_10_EXP__   4932"

.SS "#define __LDBL_MAX__   1\&.18973149535723176502126385303097021e+4932L"

.SS "#define __LDBL_MAX_EXP__   16384"

.SS "#define __LDBL_MIN_10_EXP__   (\-4931)"

.SS "#define __LDBL_MIN__   3\&.36210314311209350626267781732175260e\-4932L"

.SS "#define __LDBL_MIN_EXP__   (\-16381)"

.SS "#define __linux   1"

.SS "#define __linux__   1"

.SS "#define __LONG_LONG_MAX__   0x7fffffffffffffffLL"

.SS "#define __LONG_LONG_WIDTH__   64"

.SS "#define __LONG_MAX__   0x7fffffffffffffffL"

.SS "#define __LONG_WIDTH__   64"

.SS "#define __LP64__   1"

.SS "#define __MMX__   1"

.SS "#define __NO_INLINE__   1"

.SS "#define __ORDER_BIG_ENDIAN__   4321"

.SS "#define __ORDER_LITTLE_ENDIAN__   1234"

.SS "#define __ORDER_PDP_ENDIAN__   3412"

.SS "#define __pic__   2"

.SS "#define __PIC__   2"

.SS "#define __pie__   2"

.SS "#define __PIE__   2"

.SS "#define __PRAGMA_REDEFINE_EXTNAME   1"

.SS "#define __PTRDIFF_MAX__   0x7fffffffffffffffL"

.SS "#define __PTRDIFF_TYPE__   long int"

.SS "#define __PTRDIFF_WIDTH__   64"

.SS "#define __REGISTER_PREFIX__"

.SS "#define __SCHAR_MAX__   0x7f"

.SS "#define __SCHAR_WIDTH__   8"

.SS "#define __SEG_FS   1"

.SS "#define __SEG_GS   1"

.SS "#define __SHRT_MAX__   0x7fff"

.SS "#define __SHRT_WIDTH__   16"

.SS "#define __SIG_ATOMIC_MAX__   0x7fffffff"

.SS "#define __SIG_ATOMIC_MIN__   (\-\fB__SIG_ATOMIC_MAX__\fP \- 1)"

.SS "#define __SIG_ATOMIC_TYPE__   int"

.SS "#define __SIG_ATOMIC_WIDTH__   32"

.SS "#define __SIZE_MAX__   0xffffffffffffffffUL"

.SS "#define __SIZE_TYPE__   long unsigned int"

.SS "#define __SIZE_WIDTH__   64"

.SS "#define __SIZEOF_DOUBLE__   8"

.SS "#define __SIZEOF_FLOAT128__   16"

.SS "#define __SIZEOF_FLOAT80__   16"

.SS "#define __SIZEOF_FLOAT__   4"

.SS "#define __SIZEOF_INT128__   16"

.SS "#define __SIZEOF_INT__   4"

.SS "#define __SIZEOF_LONG__   8"

.SS "#define __SIZEOF_LONG_DOUBLE__   16"

.SS "#define __SIZEOF_LONG_LONG__   8"

.SS "#define __SIZEOF_POINTER__   8"

.SS "#define __SIZEOF_PTRDIFF_T__   8"

.SS "#define __SIZEOF_SHORT__   2"

.SS "#define __SIZEOF_SIZE_T__   8"

.SS "#define __SIZEOF_WCHAR_T__   4"

.SS "#define __SIZEOF_WINT_T__   4"

.SS "#define __SSE2__   1"

.SS "#define __SSE2_MATH__   1"

.SS "#define __SSE__   1"

.SS "#define __SSE_MATH__   1"

.SS "#define __SSP_STRONG__   3"

.SS "#define __STDC__   1"

.SS "#define __STDC_HOSTED__   1"

.SS "#define __STDC_IEC_559__   1"

.SS "#define __STDC_IEC_559_COMPLEX__   1"

.SS "#define __STDC_ISO_10646__   201706L"

.SS "#define __STDC_NO_THREADS__   1"

.SS "#define __STDC_UTF_16__   1"

.SS "#define __STDC_UTF_32__   1"

.SS "#define __UINT16_C(c)   c"

.SS "#define __UINT16_MAX__   0xffff"

.SS "#define __UINT16_TYPE__   short unsigned int"

.SS "#define __UINT32_C(c)   c ## U"

.SS "#define __UINT32_MAX__   0xffffffffU"

.SS "#define __UINT32_TYPE__   unsigned int"

.SS "#define __UINT64_C(c)   c ## UL"

.SS "#define __UINT64_MAX__   0xffffffffffffffffUL"

.SS "#define __UINT64_TYPE__   long unsigned int"

.SS "#define __UINT8_C(c)   c"

.SS "#define __UINT8_MAX__   0xff"

.SS "#define __UINT8_TYPE__   unsigned char"

.SS "#define __UINT_FAST16_MAX__   0xffffffffffffffffUL"

.SS "#define __UINT_FAST16_TYPE__   long unsigned int"

.SS "#define __UINT_FAST32_MAX__   0xffffffffffffffffUL"

.SS "#define __UINT_FAST32_TYPE__   long unsigned int"

.SS "#define __UINT_FAST64_MAX__   0xffffffffffffffffUL"

.SS "#define __UINT_FAST64_TYPE__   long unsigned int"

.SS "#define __UINT_FAST8_MAX__   0xff"

.SS "#define __UINT_FAST8_TYPE__   unsigned char"

.SS "#define __UINT_LEAST16_MAX__   0xffff"

.SS "#define __UINT_LEAST16_TYPE__   short unsigned int"

.SS "#define __UINT_LEAST32_MAX__   0xffffffffU"

.SS "#define __UINT_LEAST32_TYPE__   unsigned int"

.SS "#define __UINT_LEAST64_MAX__   0xffffffffffffffffUL"

.SS "#define __UINT_LEAST64_TYPE__   long unsigned int"

.SS "#define __UINT_LEAST8_MAX__   0xff"

.SS "#define __UINT_LEAST8_TYPE__   unsigned char"

.SS "#define __UINTMAX_C(c)   c ## UL"

.SS "#define __UINTMAX_MAX__   0xffffffffffffffffUL"

.SS "#define __UINTMAX_TYPE__   long unsigned int"

.SS "#define __UINTPTR_MAX__   0xffffffffffffffffUL"

.SS "#define __UINTPTR_TYPE__   long unsigned int"

.SS "#define __unix   1"

.SS "#define __unix__   1"

.SS "#define __USER_LABEL_PREFIX__"

.SS "#define __VERSION__   '7\&.3\&.0'"

.SS "#define __WCHAR_MAX__   0x7fffffff"

.SS "#define __WCHAR_MIN__   (\-\fB__WCHAR_MAX__\fP \- 1)"

.SS "#define __WCHAR_TYPE__   int"

.SS "#define __WCHAR_WIDTH__   32"

.SS "#define __WINT_MAX__   0xffffffffU"

.SS "#define __WINT_MIN__   0U"

.SS "#define __WINT_TYPE__   unsigned int"

.SS "#define __WINT_WIDTH__   32"

.SS "#define __x86_64   1"

.SS "#define __x86_64__   1"

.SS "#define _GNU_SOURCE   1"

.SS "#define _LP64   1"

.SS "#define _STDC_PREDEF_H   1"

.SS "#define ABI_ID   'ELF'"

.SS "#define linux   1"

.SS "#define QT_CORE_LIB   1"

.SS "#define QT_GUI_LIB   1"

.SS "#define QT_NO_DEBUG   1"

.SS "#define QT_OPENGL_LIB   1"

.SS "#define QT_SVG_LIB   1"

.SS "#define QT_WIDGETS_LIB   1"

.SS "#define SIZEOF_DPTR   (sizeof(void*))"

.SS "#define unix   1"

.SH "Author"
.PP 
Generated automatically by Doxygen for dl-DetectionSuite from the source code\&.
