.TH "MyApp" 3 "Sat Dec 15 2018" "Version 1.00" "dl-DetectionSuite" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MyApp
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSampleGenerationApp\fP, \fBSampleGenerationApp\fP, \fBSampleGenerationApp\fP, \fBSampleGenerationApp\fP, \fBSampleGenerationApp\fP, \fBSampleGenerationApp\fP, \fBSampleGenerationApp\fP, and \fBSampleGenerationApp\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMyApp\fP (int \fBargc\fP, char *\fBargv\fP[])"
.br
.ti -1c
.RI "void \fBoperator()\fP ()"
.br
.ti -1c
.RI "\fBMyApp\fP (int \fBargc\fP, char *\fBargv\fP[])"
.br
.ti -1c
.RI "virtual void \fBoperator()\fP ()"
.br
.ti -1c
.RI "\fBMyApp\fP (int \fBargc\fP, char *\fBargv\fP[])"
.br
.ti -1c
.RI "void \fBoperator()\fP ()"
.br
.ti -1c
.RI "\fBMyApp\fP (int \fBargc\fP, char *\fBargv\fP[])"
.br
.ti -1c
.RI "void \fBoperator()\fP ()"
.br
.ti -1c
.RI "\fBMyApp\fP (int \fBargc\fP, char *\fBargv\fP[])"
.br
.ti -1c
.RI "void \fBoperator()\fP ()"
.br
.ti -1c
.RI "\fBMyApp\fP (int \fBargc\fP, char *\fBargv\fP[])"
.br
.ti -1c
.RI "void \fBoperator()\fP ()"
.br
.ti -1c
.RI "\fBMyApp\fP (int \fBargc\fP, char *\fBargv\fP[])"
.br
.ti -1c
.RI "void \fBoperator()\fP ()"
.br
.ti -1c
.RI "\fBMyApp\fP (int \fBargc\fP, char *\fBargv\fP[])"
.br
.ti -1c
.RI "void \fBoperator()\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MyApp::MyApp (int argc, char * argv[])\fC [inline]\fP"

.SS "MyApp::MyApp (int argc, char * argv[])\fC [inline]\fP"

.SS "MyApp::MyApp (int argc, char * argv[])\fC [inline]\fP"

.SS "MyApp::MyApp (int argc, char * argv[])\fC [inline]\fP"

.SS "MyApp::MyApp (int argc, char * argv[])\fC [inline]\fP"

.SS "MyApp::MyApp (int argc, char * argv[])\fC [inline]\fP"

.SS "MyApp::MyApp (int argc, char * argv[])\fC [inline]\fP"

.SS "MyApp::MyApp (int argc, char * argv[])\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void MyApp::operator() ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBSampleGenerationApp\fP\&.
.SS "void MyApp::operator() ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBSampleGenerationApp\fP\&.
.SS "void MyApp::operator() ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBSampleGenerationApp\fP\&.
.SS "void MyApp::operator() ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBSampleGenerationApp\fP\&.
.SS "void MyApp::operator() ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBSampleGenerationApp\fP\&.
.SS "virtual void MyApp::operator() ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBSampleGenerationApp\fP\&.
.SS "void MyApp::operator() ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBSampleGenerationApp\fP\&.
.SS "void MyApp::operator() ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBSampleGenerationApp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for dl-DetectionSuite from the source code\&.
