.TH "Normalizations" 3 "Sat Dec 15 2018" "Version 1.00" "dl-DetectionSuite" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Normalizations
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Normalizations\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBnormalizeRect\fP (cv::Rect &region, cv::Size size)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void Normalizations::normalizeRect (cv::Rect & region, cv::Size size)\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for dl-DetectionSuite from the source code\&.
