.TH "DeepLearningSuite/DeepLearningSuiteLib/DatasetConverters/writers/PascalVOCDatasetWriter.h" 3 "Sat Dec 15 2018" "Version 1.00" "dl-DetectionSuite" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DeepLearningSuite/DeepLearningSuiteLib/DatasetConverters/writers/PascalVOCDatasetWriter.h
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include 'DatasetWriter\&.h'\fP
.br
\fC#include <boost/property_tree/ptree\&.hpp>\fP
.br
\fC#include <boost/property_tree/xml_parser\&.hpp>\fP
.br
\fC#include <boost/filesystem/path\&.hpp>\fP
.br
\fC#include <boost/filesystem/operations\&.hpp>\fP
.br
\fC#include <boost/foreach\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPascalVOCDatasetWriter\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef boost::shared_ptr< \fBPascalVOCDatasetWriter\fP > \fBPascalVOCDatasetWriterPtr\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef boost::shared_ptr<\fBPascalVOCDatasetWriter\fP> \fBPascalVOCDatasetWriterPtr\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for dl-DetectionSuite from the source code\&.
