.TH "qt_meta_stringdata_MainWindow_t" 3 "Sat Dec 15 2018" "Version 1.00" "dl-DetectionSuite" \" -*- nroff -*-
.ad l
.nh
.SH NAME
qt_meta_stringdata_MainWindow_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QByteArrayData \fBdata\fP [26]"
.br
.ti -1c
.RI "char \fBstringdata0\fP [651]"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "QByteArrayData qt_meta_stringdata_MainWindow_t::data[26]"

.SS "char qt_meta_stringdata_MainWindow_t::stringdata0[651]"


.SH "Author"
.PP 
Generated automatically by Doxygen for dl-DetectionSuite from the source code\&.
