.TH "RLE" 3 "Sat Dec 15 2018" "Version 1.00" "dl-DetectionSuite" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RLE
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <maskApi\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBsiz\fP \fBh\fP"
.br
.ti -1c
.RI "\fBsiz\fP \fBw\fP"
.br
.ti -1c
.RI "\fBsiz\fP \fBm\fP"
.br
.ti -1c
.RI "\fBuint\fP * \fBcnts\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBuint\fP* RLE::cnts"

.SS "\fBsiz\fP RLE::h"

.SS "\fBsiz\fP RLE::m"

.SS "\fBsiz\fP RLE::w"


.SH "Author"
.PP 
Generated automatically by Doxygen for dl-DetectionSuite from the source code\&.
