.TH "sampleGenerator.sample.sample" 3 "Sat Dec 15 2018" "Version 1.00" "dl-DetectionSuite" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sampleGenerator.sample.sample
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBimage\fP, roi)"
.br
.ti -1c
.RI "def \fBgetImage\fP (self)"
.br
.ti -1c
.RI "def \fBgetImageWidth\fP (self)"
.br
.ti -1c
.RI "def \fBgetImageHeight\fP (self)"
.br
.ti -1c
.RI "def \fBgetManualSegments\fP (self)"
.br
.ti -1c
.RI "def \fBgetAutoSegments\fP (self)"
.br
.ti -1c
.RI "def \fBgetAllSegments\fP (self)"
.br
.ti -1c
.RI "def \fBgetInvalidRegions\fP (self)"
.br
.ti -1c
.RI "def \fBgetImageWithData\fP (self)"
.br
.ti -1c
.RI "def \fBapplyScale\fP (self, \fBscale\fP)"
.br
.ti -1c
.RI "def \fBapplyWarp\fP (self, \fBangle\fP)"
.br
.ti -1c
.RI "def \fBapplyFlip\fP (self)"
.br
.ti -1c
.RI "def \fBgetFlip\fP (self)"
.br
.ti -1c
.RI "def \fBgetScale\fP (self)"
.br
.ti -1c
.RI "def \fBgetAngle\fP (self)"
.br
.ti -1c
.RI "def \fBprintResult\fP (self)"
.br
.ti -1c
.RI "def \fBgetResultStr\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBimage\fP"
.br
.ti -1c
.RI "\fBx\fP"
.br
.ti -1c
.RI "\fBy\fP"
.br
.ti -1c
.RI "\fBw\fP"
.br
.ti -1c
.RI "\fBh\fP"
.br
.ti -1c
.RI "\fBscale\fP"
.br
.ti -1c
.RI "\fBangle\fP"
.br
.ti -1c
.RI "\fBloaded\fP"
.br
.ti -1c
.RI "\fBflipped\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def sampleGenerator\&.sample\&.sample\&.__init__ ( self,  image,  roi)"

.SH "Member Function Documentation"
.PP 
.SS "def sampleGenerator\&.sample\&.sample\&.applyFlip ( self)"

.SS "def sampleGenerator\&.sample\&.sample\&.applyScale ( self,  scale)"

.SS "def sampleGenerator\&.sample\&.sample\&.applyWarp ( self,  angle)"

.SS "def sampleGenerator\&.sample\&.sample\&.getAllSegments ( self)"

.SS "def sampleGenerator\&.sample\&.sample\&.getAngle ( self)"

.SS "def sampleGenerator\&.sample\&.sample\&.getAutoSegments ( self)"

.SS "def sampleGenerator\&.sample\&.sample\&.getFlip ( self)"

.SS "def sampleGenerator\&.sample\&.sample\&.getImage ( self)"

.SS "def sampleGenerator\&.sample\&.sample\&.getImageHeight ( self)"

.SS "def sampleGenerator\&.sample\&.sample\&.getImageWidth ( self)"

.SS "def sampleGenerator\&.sample\&.sample\&.getImageWithData ( self)"

.SS "def sampleGenerator\&.sample\&.sample\&.getInvalidRegions ( self)"

.SS "def sampleGenerator\&.sample\&.sample\&.getManualSegments ( self)"

.SS "def sampleGenerator\&.sample\&.sample\&.getResultStr ( self)"

.SS "def sampleGenerator\&.sample\&.sample\&.getScale ( self)"

.SS "def sampleGenerator\&.sample\&.sample\&.printResult ( self)"

.SH "Member Data Documentation"
.PP 
.SS "sampleGenerator\&.sample\&.sample\&.angle"

.SS "sampleGenerator\&.sample\&.sample\&.flipped"

.SS "sampleGenerator\&.sample\&.sample\&.h"

.SS "sampleGenerator\&.sample\&.sample\&.image"

.SS "sampleGenerator\&.sample\&.sample\&.loaded"

.SS "sampleGenerator\&.sample\&.sample\&.scale"

.SS "sampleGenerator\&.sample\&.sample\&.w"

.SS "sampleGenerator\&.sample\&.sample\&.x"

.SS "sampleGenerator\&.sample\&.sample\&.y"


.SH "Author"
.PP 
Generated automatically by Doxygen for dl-DetectionSuite from the source code\&.
