.TH "SampleGeneratorHandler::Converter" 3 "Sat Dec 15 2018" "Version 1.00" "dl-DetectionSuite" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SampleGeneratorHandler::Converter
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Converter\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBprocess\fP (QListView *datasetList, QListView *namesList, QListView *readerImpList, QListView *filterClasses, QListView *writerImpList, QListView *writerNamesList, bool useWriterNames, const std::string &datasetPath, const std::string &namesPath, const std::string &outputPath, bool splitActive, double splitRatio, bool writeImages)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void SampleGeneratorHandler::Converter::process (QListView * datasetList, QListView * namesList, QListView * readerImpList, QListView * filterClasses, QListView * writerImpList, QListView * writerNamesList, bool useWriterNames, const std::string & datasetPath, const std::string & namesPath, const std::string & outputPath, bool splitActive, double splitRatio, bool writeImages)\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for dl-DetectionSuite from the source code\&.
