.TH "SampleGeneratorHandler::Deployer" 3 "Sat Dec 15 2018" "Version 1.00" "dl-DetectionSuite" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SampleGeneratorHandler::Deployer
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Deployer\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBprocess\fP (QListView *deployImpList, QListView *weightsList, QListView *netConfigList, QListView *inferencerImpList, QListView *inferencerNamesList, bool *stopButton, double *confidence_threshold, QGroupBox *deployer_params, QGroupBox *camera_params, QGroupBox *inferencer_params, const std::string &weightsPath, const std::string &cfgPath, const std::string &inferencerNamesPath, const std::string &inputInfo, const std::string &outputFolder)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void SampleGeneratorHandler::Deployer::process (QListView * deployImpList, QListView * weightsList, QListView * netConfigList, QListView * inferencerImpList, QListView * inferencerNamesList, bool * stopButton, double * confidence_threshold, QGroupBox * deployer_params, QGroupBox * camera_params, QGroupBox * inferencer_params, const std::string & weightsPath, const std::string & cfgPath, const std::string & inferencerNamesPath, const std::string & inputInfo, const std::string & outputFolder)\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for dl-DetectionSuite from the source code\&.
