.TH "SpinelloDatasetReader" 3 "Sat Dec 15 2018" "Version 1.00" "dl-DetectionSuite" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SpinelloDatasetReader
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SpinelloDatasetReader\&.h>\fP
.PP
Inherits \fBDatasetReader\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSpinelloDatasetReader\fP (const std::string &path, const std::string &\fBclassNamesFile\fP, const bool \fBimagesRequired\fP)"
.br
.ti -1c
.RI "\fBSpinelloDatasetReader\fP (const bool \fBimagesRequired\fP)"
.br
.ti -1c
.RI "bool \fBappendDataset\fP (const std::string &datasetPath, const std::string &datasetPrefix='')"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SpinelloDatasetReader::SpinelloDatasetReader (const std::string & path, const std::string & classNamesFile, const bool imagesRequired)"

.SS "SpinelloDatasetReader::SpinelloDatasetReader (const bool imagesRequired)"

.SH "Member Function Documentation"
.PP 
.SS "bool SpinelloDatasetReader::appendDataset (const std::string & datasetPath, const std::string & datasetPrefix = \fC''\fP)\fC [virtual]\fP"

.PP
Reimplemented from \fBDatasetReader\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for dl-DetectionSuite from the source code\&.
