.TH "StatsWriter" 3 "Sat Dec 15 2018" "Version 1.00" "dl-DetectionSuite" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StatsWriter
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <StatsWriter\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStatsWriter\fP (\fBDatasetReaderPtr\fP dataset, std::string &writerFile)"
.br
.ti -1c
.RI "void \fBwriteInferencerResults\fP (std::string inferencerName, \fBDetectionsEvaluatorPtr\fP evaluator)"
.br
.ti -1c
.RI "void \fBsaveFile\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "StatsWriter::StatsWriter (\fBDatasetReaderPtr\fP dataset, std::string & writerFile)"

.SH "Member Function Documentation"
.PP 
.SS "void StatsWriter::saveFile ()"

.SS "void StatsWriter::writeInferencerResults (std::string inferencerName, \fBDetectionsEvaluatorPtr\fP evaluator)"


.SH "Author"
.PP 
Generated automatically by Doxygen for dl-DetectionSuite from the source code\&.
