.TH "std" 3 "Sat Dec 15 2018" "Version 1.00" "dl-DetectionSuite" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "vector< string > \fBsplit\fP (string str, string del)"
.br
.ti -1c
.RI "bool \fBfileexists\fP (std::string filepath)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Fallback \fBstd::split\fP source: http://stackoverflow.com/questions/5607589/right-way-to-split-an-stdstring-into-a-vectorstring
.PP
Check if file exists For Linux works for files and directories source: http://www.cplusplus.com/forum/general/1796/ 
.SH "Function Documentation"
.PP 
.SS "bool std::fileexists (std::string filepath)\fC [inline]\fP"

.SS "vector<string> std::split (string str, string del)\fC [inline]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for dl-DetectionSuite from the source code\&.
