.TH "DeepLearningSuite/DatasetEvaluationApp/gui/TabHandler.cpp" 3 "Sat Dec 15 2018" "Version 1.00" "dl-DetectionSuite" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DeepLearningSuite/DatasetEvaluationApp/gui/TabHandler.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <glog/logging\&.h>\fP
.br
\fC#include <DatasetConverters/readers/GenericDatasetReader\&.h>\fP
.br
\fC#include 'TabHandler\&.h'\fP
.br
\fC#include 'ListViewConfig\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for dl-DetectionSuite from the source code\&.
