.TH "TensorFlowInferencer" 3 "Sat Dec 15 2018" "Version 1.00" "dl-DetectionSuite" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TensorFlowInferencer
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TensorFlowInferencer\&.h>\fP
.PP
Inherits \fBFrameworkInferencer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTensorFlowInferencer\fP (const std::string &netConfig, const std::string &netWeights, const std::string &\fBclassNamesFile\fP)"
.br
.ti -1c
.RI "\fBSample\fP \fBdetectImp\fP (const cv::Mat &image, double confidence_threshold)"
.br
.ti -1c
.RI "int \fBgettfInferences\fP (const cv::Mat &image, double confidence_threshold)"
.br
.ti -1c
.RI "void \fBoutput_result\fP (int num_detections, int width, int height, PyObject *bounding_boxes, PyObject *detection_scores, PyObject *classIds, PyObject *detections_masks=NULL)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBinit\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TensorFlowInferencer::TensorFlowInferencer (const std::string & netConfig, const std::string & netWeights, const std::string & classNamesFile)"

.SH "Member Function Documentation"
.PP 
.SS "\fBSample\fP TensorFlowInferencer::detectImp (const cv::Mat & image, double confidence_threshold)\fC [virtual]\fP"

.PP
Implements \fBFrameworkInferencer\fP\&.
.SS "int TensorFlowInferencer::gettfInferences (const cv::Mat & image, double confidence_threshold)"

.SS "void TensorFlowInferencer::init ()\fC [static]\fP"

.SS "void TensorFlowInferencer::output_result (int num_detections, int width, int height, PyObject * bounding_boxes, PyObject * detection_scores, PyObject * classIds, PyObject * detections_masks = \fCNULL\fP)"


.SH "Author"
.PP 
Generated automatically by Doxygen for dl-DetectionSuite from the source code\&.
