.TH "DeepLearningSuite/build/DatasetEvaluationApp/DatasetEvaluationApp_autogen/include/ui_mainwindow.h" 3 "Sat Dec 15 2018" "Version 1.00" "dl-DetectionSuite" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DeepLearningSuite/build/DatasetEvaluationApp/DatasetEvaluationApp_autogen/include/ui_mainwindow.h
.SH SYNOPSIS
.br
.PP
\fC#include <QtCore/QVariant>\fP
.br
\fC#include <QtWidgets/QAction>\fP
.br
\fC#include <QtWidgets/QApplication>\fP
.br
\fC#include <QtWidgets/QButtonGroup>\fP
.br
\fC#include <QtWidgets/QCheckBox>\fP
.br
\fC#include <QtWidgets/QFrame>\fP
.br
\fC#include <QtWidgets/QGroupBox>\fP
.br
\fC#include <QtWidgets/QHeaderView>\fP
.br
\fC#include <QtWidgets/QLabel>\fP
.br
\fC#include <QtWidgets/QLineEdit>\fP
.br
\fC#include <QtWidgets/QListView>\fP
.br
\fC#include <QtWidgets/QMainWindow>\fP
.br
\fC#include <QtWidgets/QMenuBar>\fP
.br
\fC#include <QtWidgets/QPushButton>\fP
.br
\fC#include <QtWidgets/QRadioButton>\fP
.br
\fC#include <QtWidgets/QSlider>\fP
.br
\fC#include <QtWidgets/QSpinBox>\fP
.br
\fC#include <QtWidgets/QStatusBar>\fP
.br
\fC#include <QtWidgets/QTabWidget>\fP
.br
\fC#include <QtWidgets/QTextEdit>\fP
.br
\fC#include <QtWidgets/QToolBar>\fP
.br
\fC#include <QtWidgets/QVBoxLayout>\fP
.br
\fC#include <QtWidgets/QWidget>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBUi_MainWindow\fP"
.br
.ti -1c
.RI "class \fBUi::MainWindow\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for dl-DetectionSuite from the source code\&.
