.TH "Utils" 3 "Sat Dec 15 2018" "Version 1.00" "dl-DetectionSuite" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Utils
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Utils\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBgetListViewContent\fP (const QListView *list, std::vector< std::string > &content, const std::string &prefix)"
.br
.ti -1c
.RI "static bool \fBgetDeployerParamsContent\fP (const QGroupBox *deployer_params, std::map< std::string, std::string > &deployer_params_map)"
.br
.ti -1c
.RI "static bool \fBgetInferencerParamsContent\fP (const QGroupBox *inferencer_params, std::map< std::string, std::string > &inferencer_params_map)"
.br
.ti -1c
.RI "static bool \fBgetCameraParamsContent\fP (const QGroupBox *camera_params, int &cameraID)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "bool Utils::getCameraParamsContent (const QGroupBox * camera_params, int & cameraID)\fC [static]\fP"

.SS "bool Utils::getDeployerParamsContent (const QGroupBox * deployer_params, std::map< std::string, std::string > & deployer_params_map)\fC [static]\fP"

.SS "bool Utils::getInferencerParamsContent (const QGroupBox * inferencer_params, std::map< std::string, std::string > & inferencer_params_map)\fC [static]\fP"

.SS "bool Utils::getListViewContent (const QListView * list, std::vector< std::string > & content, const std::string & prefix)\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for dl-DetectionSuite from the source code\&.
