name: Run tests automatically

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'  

      - name: Cache pytest
        uses: actions/cache@v3
        with:
          path: |
            .pytest_cache
            __pycache__
          key: ${{ runner.os }}-pytest-${{ hashFiles('**/*.py') }}
          restore-keys: |
            ${{ runner.os }}-pytest-

      - name: Install dependencies
        run: python -m pip install pytest .

      - name: Run tests
        run: pytest
